// Code generated by sgen.exe,2022-11-11 13:37:04. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package service

import (
	"context"
	"errors"

	"go-micro.dev/v4/logger"
	"gorm.io/gen/field"

	"cloud_platform/iot_intelligence_service/convert"
	iotmodel "cloud_platform/iot_model"
	"cloud_platform/iot_model/db_device/model"
	"cloud_platform/iot_model/db_device/orm"
	proto "cloud_platform/iot_proto/protos/protosService"
)

type SceneTemplateTaskSvc struct {
	Ctx context.Context
}

// 创建SceneTemplateTask
func (s *SceneTemplateTaskSvc) CreateSceneTemplateTask(req *proto.SceneTemplateTask) (*proto.SceneTemplateTask, error) {
	// fixme 请在这里校验参数
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	dbObj := convert.SceneTemplateTask_pb2db(req)
	err := do.Create(dbObj)
	if err != nil {
		logger.Errorf("CreateSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据条件删除SceneTemplateTask
func (s *SceneTemplateTaskSvc) DeleteSceneTemplateTask(req *proto.SceneTemplateTask) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.SceneTemplateId != 0 { //整数
		do = do.Where(t.SceneTemplateId.Eq(req.SceneTemplateId))
	}
	if req.ProductId != 0 { //整数
		do = do.Where(t.ProductId.Eq(req.ProductId))
	}
	if req.ProductKey != "" { //字符串
		do = do.Where(t.ProductKey.Eq(req.ProductKey))
	}
	if req.Functions != "" { //字符串
		do = do.Where(t.Functions.Eq(req.Functions))
	}
	if req.Sort != 0 { //整数
		do = do.Where(t.Sort.Eq(req.Sort))
	}
	if req.CreatedBy != 0 { //整数
		do = do.Where(t.CreatedBy.Eq(req.CreatedBy))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键删除SceneTemplateTask
func (s *SceneTemplateTaskSvc) DeleteByIdSceneTemplateTask(req *proto.SceneTemplateTask) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteByIdSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键批量删除SceneTemplateTask
func (s *SceneTemplateTaskSvc) DeleteByIdsSceneTemplateTask(req *proto.SceneTemplateTaskBatchDeleteRequest) (*proto.SceneTemplateTaskBatchDeleteRequest, error) {
	var err error
	for _, k := range req.Keys {
		t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
		do := t.WithContext(context.Background())

		do = do.Where(t.Id.Eq(k.Id))

		_, err = do.Delete()
		if err != nil {
			logger.Errorf("DeleteByIdsSceneTemplateTask error : %s", err.Error())
			break
		}
	}
	return req, err
}

// 根据主键更新SceneTemplateTask
func (s *SceneTemplateTaskSvc) UpdateSceneTemplateTask(req *proto.SceneTemplateTask) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	if req.SceneTemplateId != 0 { //整数
		updateField = append(updateField, t.SceneTemplateId)
	}
	if req.ProductId != 0 { //整数
		updateField = append(updateField, t.ProductId)
	}
	if req.ProductKey != "" { //字符串
		updateField = append(updateField, t.ProductKey)
	}
	if req.Functions != "" { //字符串
		updateField = append(updateField, t.Functions)
	}
	if req.Sort != 0 { //整数
		updateField = append(updateField, t.Sort)
	}
	if req.CreatedBy != 0 { //整数
		updateField = append(updateField, t.CreatedBy)
	}
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}

	if !HasPrimaryKey {
		logger.Error("UpdateSceneTemplateTask error : Missing condition")
		return nil, errors.New("Missing condition")
	}

	dbObj := convert.SceneTemplateTask_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// //根据主键更新所有字段SceneTemplateTask
func (s *SceneTemplateTaskSvc) UpdateAllSceneTemplateTask(req *proto.SceneTemplateTask) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	updateField = append(updateField, t.SceneTemplateId)
	updateField = append(updateField, t.ProductId)
	updateField = append(updateField, t.ProductKey)
	updateField = append(updateField, t.Functions)
	updateField = append(updateField, t.Sort)
	updateField = append(updateField, t.CreatedBy)
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false
	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateAllSceneTemplateTask error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.SceneTemplateTask_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateAllSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req, err
}

func (s *SceneTemplateTaskSvc) UpdateFieldsSceneTemplateTask(req *proto.SceneTemplateTaskUpdateFieldsRequest) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())

	var updateField []field.Expr
	for _, v := range req.Fields {
		col, ok := t.GetFieldByName(v)
		if ok {
			updateField = append(updateField, col)
		}
	}
	if len(updateField) == 0 {
		err := errors.New("UpdateFieldsSceneTemplateTask error : missing updateField")
		logger.Error(err)
		return nil, err
	}
	do = do.Select(updateField...)

	//主键条件
	HasPrimaryKey := false
	if req.Data.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Data.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateFieldsSceneTemplateTask error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.SceneTemplateTask_pb2db(req.Data)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateFieldsSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	return req.Data, nil
}

// 根据非空条件查找SceneTemplateTask
func (s *SceneTemplateTaskSvc) FindSceneTemplateTask(req *proto.SceneTemplateTaskFilter) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.SceneTemplateId != 0 { //整数
		do = do.Where(t.SceneTemplateId.Eq(req.SceneTemplateId))
	}
	if req.ProductId != 0 { //整数
		do = do.Where(t.ProductId.Eq(req.ProductId))
	}
	if req.ProductKey != "" { //字符串
		do = do.Where(t.ProductKey.Eq(req.ProductKey))
	}
	if req.Functions != "" { //字符串
		do = do.Where(t.Functions.Eq(req.Functions))
	}
	if req.Sort != 0 { //整数
		do = do.Where(t.Sort.Eq(req.Sort))
	}
	if req.CreatedBy != 0 { //整数
		do = do.Where(t.CreatedBy.Eq(req.CreatedBy))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	res := convert.SceneTemplateTask_db2pb(dbObj)
	return res, err
}

// 根据数据库表主键查找SceneTemplateTask
func (s *SceneTemplateTaskSvc) FindByIdSceneTemplateTask(req *proto.SceneTemplateTaskFilter) (*proto.SceneTemplateTask, error) {
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindByIdSceneTemplateTask error : %s", err.Error())
		return nil, err
	}
	res := convert.SceneTemplateTask_db2pb(dbObj)
	return res, err
}

// 根据分页条件查找SceneTemplateTask,请确保req.Query的结构字段与数据表model结构体字段保持一致，否则会有编译问题
func (s *SceneTemplateTaskSvc) GetListSceneTemplateTask(req *proto.SceneTemplateTaskListRequest) ([]*proto.SceneTemplateTask, int64, error) {
	// fixme 请检查条件和校验参数
	var err error
	t := orm.Use(iotmodel.GetDB()).TSceneTemplateTask
	do := t.WithContext(context.Background())
	query := req.Query
	if query != nil {

		if query.Id != 0 { //整数
			do = do.Where(t.Id.Eq(query.Id))
		}
		if query.SceneTemplateId != 0 { //整数
			do = do.Where(t.SceneTemplateId.Eq(query.SceneTemplateId))
		}
		if query.ProductId != 0 { //整数
			do = do.Where(t.ProductId.Eq(query.ProductId))
		}
		if query.ProductKey != "" { //字符串
			do = do.Where(t.ProductKey.Like("%" + query.ProductKey + "%"))
		}
		if query.Functions != "" { //字符串
			do = do.Where(t.Functions.Like("%" + query.Functions + "%"))
		}
		if query.Sort != 0 { //整数
			do = do.Where(t.Sort.Eq(query.Sort))
		}
		if query.CreatedBy != 0 { //整数
			do = do.Where(t.CreatedBy.Eq(query.CreatedBy))
		}
	}
	orderCol, ok := t.GetFieldByName(req.OrderKey)
	if !ok {
		orderCol = t.Id
	}
	if req.OrderDesc != "" {
		do = do.Order(orderCol.Desc())
	} else {
		do = do.Order(orderCol)
	}

	var list []*model.TSceneTemplateTask
	var total int64
	if req.PageSize > 0 {
		limit := req.PageSize
		if req.Page == 0 {
			req.Page = 1
		}
		offset := req.PageSize * (req.Page - 1)
		list, total, err = do.FindByPage(int(offset), int(limit))
	} else {
		list, err = do.Find()
		total = int64(len(list))
	}
	if err != nil {
		logger.Errorf("GetListSceneTemplateTask error : %s", err.Error())
		return nil, 0, err
	}
	if len(list) == 0 {
		return nil, total, nil
	}
	result := make([]*proto.SceneTemplateTask, len(list))
	for i, v := range list {
		result[i] = convert.SceneTemplateTask_db2pb(v)
	}
	return result, total, nil
}
