// Code generated by sgen.exe,2022-04-18 21:26:14. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package service

import (
	"context"
	"errors"

	"go-micro.dev/v4/logger"
	"gorm.io/gen/field"

	"cloud_platform/iot_app_user_service/convert"
	iotmodel "cloud_platform/iot_model"
	"cloud_platform/iot_model/db_app/model"
	"cloud_platform/iot_model/db_app/orm"
	proto "cloud_platform/iot_proto/protos/protosService"
)

type AppUpgradeSvc struct {
	Ctx context.Context
}

// 创建AppUpgrade
func (s *AppUpgradeSvc) CreateAppUpgrade(req *proto.AppUpgrade) (*proto.AppUpgrade, error) {
	// fixme 请在这里校验参数
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	dbObj := convert.AppUpgrade_pb2db(req)
	err := do.Create(dbObj)
	if err != nil {
		logger.Errorf("CreateAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据条件删除AppUpgrade
func (s *AppUpgradeSvc) DeleteAppUpgrade(req *proto.AppUpgrade) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.Name != "" { //字符串
		do = do.Where(t.Name.Eq(req.Name))
	}
	if req.Type != 0 { //整数
		do = do.Where(t.Type.Eq(req.Type))
	}
	if req.Version != "" { //字符串
		do = do.Where(t.Version.Eq(req.Version))
	}
	if req.UpgradeMode != 0 { //整数
		do = do.Where(t.UpgradeMode.Eq(req.UpgradeMode))
	}
	if req.UpgradePrompt != "" { //字符串
		do = do.Where(t.UpgradePrompt.Eq(req.UpgradePrompt))
	}
	if req.PublishType != 0 { //整数
		do = do.Where(t.PublishType.Eq(req.PublishType))
	}
	if req.Url != "" { //字符串
		do = do.Where(t.Url.Eq(req.Url))
	}
	if req.AppstoreUrl != "" { //字符串
		do = do.Where(t.AppstoreUrl.Eq(req.AppstoreUrl))
	}
	if req.MinimumRequired != "" { //字符串
		do = do.Where(t.MinimumRequired.Eq(req.MinimumRequired))
	}
	if req.ForceUpgradeVersion != "" { //字符串
		do = do.Where(t.ForceUpgradeVersion.Eq(req.ForceUpgradeVersion))
	}
	if req.FileMd5 != "" { //字符串
		do = do.Where(t.FileMd5.Eq(req.FileMd5))
	}
	if req.CreatedBy != 0 { //整数
		do = do.Where(t.CreatedBy.Eq(req.CreatedBy))
	}
	if req.UpdatedBy != 0 { //整数
		do = do.Where(t.UpdatedBy.Eq(req.UpdatedBy))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键删除AppUpgrade
func (s *AppUpgradeSvc) DeleteByIdAppUpgrade(req *proto.AppUpgrade) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteByIdAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键批量删除AppUpgrade
func (s *AppUpgradeSvc) DeleteByIdsAppUpgrade(req *proto.AppUpgradeBatchDeleteRequest) (*proto.AppUpgradeBatchDeleteRequest, error) {
	var err error
	for _, k := range req.Keys {
		t := orm.Use(iotmodel.GetDB()).TAppUpgrade
		do := t.WithContext(context.Background())

		do = do.Where(t.Id.Eq(k.Id))

		_, err = do.Delete()
		if err != nil {
			logger.Errorf("DeleteByIdsAppUpgrade error : %s", err.Error())
			break
		}
	}
	return req, err
}

// 根据主键更新AppUpgrade
func (s *AppUpgradeSvc) UpdateAppUpgrade(req *proto.AppUpgrade) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	if req.Name != "" { //字符串
		updateField = append(updateField, t.Name)
	}
	if req.Type != 0 { //整数
		updateField = append(updateField, t.Type)
	}
	if req.Version != "" { //字符串
		updateField = append(updateField, t.Version)
	}
	if req.UpgradeMode != 0 { //整数
		updateField = append(updateField, t.UpgradeMode)
	}
	if req.UpgradePrompt != "" { //字符串
		updateField = append(updateField, t.UpgradePrompt)
	}
	if req.PublishType != 0 { //整数
		updateField = append(updateField, t.PublishType)
	}
	if req.Url != "" { //字符串
		updateField = append(updateField, t.Url)
	}
	if req.AppstoreUrl != "" { //字符串
		updateField = append(updateField, t.AppstoreUrl)
	}
	if req.MinimumRequired != "" { //字符串
		updateField = append(updateField, t.MinimumRequired)
	}
	if req.ForceUpgradeVersion != "" { //字符串
		updateField = append(updateField, t.ForceUpgradeVersion)
	}
	if req.FileMd5 != "" { //字符串
		updateField = append(updateField, t.FileMd5)
	}
	if req.CreatedBy != 0 { //整数
		updateField = append(updateField, t.CreatedBy)
	}
	if req.UpdatedBy != 0 { //整数
		updateField = append(updateField, t.UpdatedBy)
	}
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}

	if !HasPrimaryKey {
		logger.Error("UpdateAppUpgrade error : Missing condition")
		return nil, errors.New("Missing condition")
	}

	dbObj := convert.AppUpgrade_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// //根据主键更新所有字段AppUpgrade
func (s *AppUpgradeSvc) UpdateAllAppUpgrade(req *proto.AppUpgrade) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	updateField = append(updateField, t.Name)
	updateField = append(updateField, t.Type)
	updateField = append(updateField, t.Version)
	updateField = append(updateField, t.UpgradeMode)
	updateField = append(updateField, t.UpgradePrompt)
	updateField = append(updateField, t.UploadTime)
	updateField = append(updateField, t.PublishTime)
	updateField = append(updateField, t.PublishType)
	updateField = append(updateField, t.Url)
	updateField = append(updateField, t.AppstoreUrl)
	updateField = append(updateField, t.MinimumRequired)
	updateField = append(updateField, t.ForceUpgradeVersion)
	updateField = append(updateField, t.FileMd5)
	updateField = append(updateField, t.CreatedBy)
	updateField = append(updateField, t.UpdatedBy)
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false
	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateAllAppUpgrade error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.AppUpgrade_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateAllAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req, err
}

func (s *AppUpgradeSvc) UpdateFieldsAppUpgrade(req *proto.AppUpgradeUpdateFieldsRequest) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())

	var updateField []field.Expr
	for _, v := range req.Fields {
		col, ok := t.GetFieldByName(v)
		if ok {
			updateField = append(updateField, col)
		}
	}
	if len(updateField) == 0 {
		err := errors.New("UpdateFields error : missing updateField")
		logger.Error(err)
		return nil, err
	}
	do = do.Select(updateField...)
	//主键条件
	HasPrimaryKey := false
	if req.Data.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Data.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateFieldsAppUpgrade error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.AppUpgrade_pb2db(req.Data)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateFieldsAppUpgrade error : %s", err.Error())
		return nil, err
	}
	return req.Data, nil
}

// 根据非空条件查找AppUpgrade
func (s *AppUpgradeSvc) FindAppUpgrade(req *proto.AppUpgradeFilter) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.Name != "" { //字符串
		do = do.Where(t.Name.Like("%" + req.Name + "%"))
	}
	if req.Type != 0 { //整数
		do = do.Where(t.Type.Eq(req.Type))
	}
	if req.Version != "" { //字符串
		do = do.Where(t.Version.Like("%" + req.Version + "%"))
	}
	if req.UpgradeMode != 0 { //整数
		do = do.Where(t.UpgradeMode.Eq(req.UpgradeMode))
	}
	if req.UpgradePrompt != "" { //字符串
		do = do.Where(t.UpgradePrompt.Like("%" + req.UpgradePrompt + "%"))
	}
	if req.PublishType != 0 { //整数
		do = do.Where(t.PublishType.Eq(req.PublishType))
	}
	if req.Url != "" { //字符串
		do = do.Where(t.Url.Like("%" + req.Url + "%"))
	}
	if req.AppstoreUrl != "" { //字符串
		do = do.Where(t.AppstoreUrl.Like("%" + req.AppstoreUrl + "%"))
	}
	if req.MinimumRequired != "" { //字符串
		do = do.Where(t.MinimumRequired.Like("%" + req.MinimumRequired + "%"))
	}
	if req.ForceUpgradeVersion != "" { //字符串
		do = do.Where(t.ForceUpgradeVersion.Like("%" + req.ForceUpgradeVersion + "%"))
	}
	if req.FileMd5 != "" { //字符串
		do = do.Where(t.FileMd5.Like("%" + req.FileMd5 + "%"))
	}
	if req.CreatedBy != 0 { //整数
		do = do.Where(t.CreatedBy.Eq(req.CreatedBy))
	}
	if req.UpdatedBy != 0 { //整数
		do = do.Where(t.UpdatedBy.Eq(req.UpdatedBy))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindAppUpgrade error : %s", err.Error())
		return nil, err
	}
	res := convert.AppUpgrade_db2pb(dbObj)
	return res, err
}

// 根据数据库表主键查找AppUpgrade
func (s *AppUpgradeSvc) FindByIdAppUpgrade(req *proto.AppUpgradeFilter) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindByIdAppUpgrade error : %s", err.Error())
		return nil, err
	}
	res := convert.AppUpgrade_db2pb(dbObj)
	return res, err
}

// 根据分页条件查找AppUpgrade,请确保req.Query的结构字段与数据表model结构体字段保持一致，否则会有编译问题
func (s *AppUpgradeSvc) GetListAppUpgrade(req *proto.AppUpgradeListRequest) ([]*proto.AppUpgrade, int64, error) {
	// fixme 请检查条件和校验参数
	var err error
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	query := req.Query
	if query != nil {

		if query.Id != 0 { //整数
			do = do.Where(t.Id.Eq(query.Id))
		}
		if query.Name != "" { //字符串
			do = do.Where(t.Name.Like("%" + query.Name + "%"))
		}
		if query.Type != 0 { //整数
			do = do.Where(t.Type.Eq(query.Type))
		}
		if query.Version != "" { //字符串
			do = do.Where(t.Version.Like("%" + query.Version + "%"))
		}
		if query.UpgradeMode != 0 { //整数
			do = do.Where(t.UpgradeMode.Eq(query.UpgradeMode))
		}
		if query.UpgradePrompt != "" { //字符串
			do = do.Where(t.UpgradePrompt.Like("%" + query.UpgradePrompt + "%"))
		}
		if query.PublishType != 0 { //整数
			do = do.Where(t.PublishType.Eq(query.PublishType))
		}
		if query.Url != "" { //字符串
			do = do.Where(t.Url.Like("%" + query.Url + "%"))
		}
		if query.AppstoreUrl != "" { //字符串
			do = do.Where(t.AppstoreUrl.Like("%" + query.AppstoreUrl + "%"))
		}
		if query.MinimumRequired != "" { //字符串
			do = do.Where(t.MinimumRequired.Like("%" + query.MinimumRequired + "%"))
		}
		if query.ForceUpgradeVersion != "" { //字符串
			do = do.Where(t.ForceUpgradeVersion.Like("%" + query.ForceUpgradeVersion + "%"))
		}
		if query.FileMd5 != "" { //字符串
			do = do.Where(t.FileMd5.Like("%" + query.FileMd5 + "%"))
		}
		if query.CreatedBy != 0 { //整数
			do = do.Where(t.CreatedBy.Eq(query.CreatedBy))
		}
		if query.UpdatedBy != 0 { //整数
			do = do.Where(t.UpdatedBy.Eq(query.UpdatedBy))
		}
	}
	orderCol, ok := t.GetFieldByName(req.OrderKey)
	if !ok {
		orderCol = t.Id
	}
	if req.OrderDesc != "" {
		do = do.Order(orderCol.Desc())
	} else {
		do = do.Order(orderCol)
	}

	var list []*model.TAppUpgrade
	var total int64
	if req.PageSize > 0 {
		limit := req.PageSize
		if req.Page == 0 {
			req.Page = 1
		}
		offset := req.PageSize * (req.Page - 1)
		list, total, err = do.FindByPage(int(offset), int(limit))
	} else {
		list, err = do.Find()
		total = int64(len(list))
	}
	if err != nil {
		logger.Errorf("GetListAppUpgrade error : %s", err.Error())
		return nil, 0, err
	}
	if len(list) == 0 {
		return nil, total, nil
	}
	result := make([]*proto.AppUpgrade, len(list))
	for i, v := range list {
		result[i] = convert.AppUpgrade_db2pb(v)
	}
	return result, total, nil
}

// 根据app类型查询最新的app版本
func (s *AppUpgradeSvc) FindLatestAppUpgrade(req *proto.LatestAppUpgradeFilter) (*proto.AppUpgrade, error) {
	t := orm.Use(iotmodel.GetDB()).TAppUpgrade
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Type != 0 { //整数
		do = do.Where(t.Type.Eq(req.Type))
	}
	orderCol, ok := t.GetFieldByName("publish_time")
	if !ok {
		orderCol = t.Id
	}
	do = do.Order(orderCol.Desc())
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindLatestAppUpgrade error : %s", err.Error())
		return nil, err
	}
	res := convert.AppUpgrade_db2pb(dbObj)
	return res, err
}
