// Code generated by sgen.exe,2022-04-18 19:12:07. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package convert

import (
	"cloud_platform/iot_model/db_system/model"
	proto "cloud_platform/iot_proto/protos/protosService"
)

func PluginsManage_pb2db(src *proto.PluginsManage) *model.TPluginsManage {
	if src == nil {
		return nil
	}
	dbObj := model.TPluginsManage{
		Id:            src.Id,
		StoreId:       src.StoreId,
		PName:         src.PName,
		PTitle:        src.PTitle,
		PDescription:  src.PDescription,
		PAuth:         src.PAuth,
		IsInstall:     src.IsInstall,
		Status:        src.Status,
		Version:       src.Version,
		Price:         src.Price,
		DownloadTimes: src.DownloadTimes,
		InstallPath:   src.InstallPath,
	}
	return &dbObj
}

func PluginsManage_db2pb(src *model.TPluginsManage) *proto.PluginsManage {
	if src == nil {
		return nil
	}
	pbObj := proto.PluginsManage{
		Id:            src.Id,
		StoreId:       src.StoreId,
		PName:         src.PName,
		PTitle:        src.PTitle,
		PDescription:  src.PDescription,
		PAuth:         src.PAuth,
		IsInstall:     src.IsInstall,
		Status:        src.Status,
		Version:       src.Version,
		Price:         src.Price,
		DownloadTimes: src.DownloadTimes,
		InstallPath:   src.InstallPath,
	}
	return &pbObj
}
