// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTSceneTemplateTask = "t_scene_template_task"

// TSceneTemplateTask mapped from table <t_scene_template_task>
type TSceneTemplateTask struct {
	Id              int64     `gorm:"column:id;primaryKey" json:"id"`                        // 唯一主键
	SceneTemplateId int64     `gorm:"column:scene_template_id" json:"sceneTemplateId"`       // 场景模板编号
	ProductId       int64     `gorm:"column:product_id" json:"productId"`                    // 产品编号
	ProductKey      string    `gorm:"column:product_key" json:"productKey"`                  // 产品Key
	Functions       string    `gorm:"column:functions" json:"functions"`                     // 功能集合json（替换func_key和func_value） { "1":true, "2": 1 }
	Sort            int32     `gorm:"column:sort" json:"sort"`                               // 排序
	CreatedBy       int64     `gorm:"column:created_by;not null;default:0" json:"createdBy"` // 创建人
	CreatedAt       time.Time `gorm:"column:created_at" json:"createdAt"`                    // 创建时间
}

// TableName TSceneTemplateTask's table name
func (*TSceneTemplateTask) TableName() string {
	return TableNameTSceneTemplateTask
}
