// Code generated by sgen.exe,2022-07-25 09:29:22. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package service

import (
	"context"
	"errors"

	"go-micro.dev/v4/logger"
	"gorm.io/gen/field"

	iotmodel "cloud_platform/iot_model"
	"cloud_platform/iot_model/db_system/model"
	"cloud_platform/iot_model/db_system/orm"
	proto "cloud_platform/iot_proto/protos/protosService"
	"cloud_platform/iot_system_service/convert"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

type SysAppEntrySvc struct {
	Ctx context.Context
}

// 创建SysAppEntry
func (s *SysAppEntrySvc) CreateSysAppEntry(req *proto.SysAppEntry) (*proto.SysAppEntry, error) {
	// fixme 请在这里校验参数
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	dbObj := convert.SysAppEntry_pb2db(req)
	err := do.Create(dbObj)
	if err != nil {
		logger.Errorf("CreateSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据条件删除SysAppEntry
func (s *SysAppEntrySvc) DeleteSysAppEntry(req *proto.SysAppEntry) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.Lang != "" { //字符串
		do = do.Where(t.Lang.Eq(req.Lang))
	}
	if req.Title != "" { //字符串
		do = do.Where(t.Title.Eq(req.Title))
	}
	if req.Content != "" { //字符串
		do = do.Where(t.Content.Eq(req.Content))
	}
	if req.SetingId != 0 { //整数
		do = do.Where(t.SetingId.Eq(req.SetingId))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键删除SysAppEntry
func (s *SysAppEntrySvc) DeleteByIdSysAppEntry(req *proto.SysAppEntry) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	_, err := do.Delete()
	if err != nil {
		logger.Errorf("DeleteByIdSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// 根据数据库表主键批量删除SysAppEntry
func (s *SysAppEntrySvc) DeleteByIdsSysAppEntry(req *proto.SysAppEntryBatchDeleteRequest) (*proto.SysAppEntryBatchDeleteRequest, error) {
	var err error
	for _, k := range req.Keys {
		t := orm.Use(iotmodel.GetDB()).TSysAppEntry
		do := t.WithContext(context.Background())

		do = do.Where(t.Id.Eq(k.Id))

		_, err = do.Delete()
		if err != nil {
			logger.Errorf("DeleteByIdsSysAppEntry error : %s", err.Error())
			break
		}
	}
	return req, err
}

// 根据主键更新SysAppEntry
func (s *SysAppEntrySvc) UpdateSysAppEntry(req *proto.SysAppEntry) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	if req.Lang != "" { //字符串
		updateField = append(updateField, t.Lang)
	}
	if req.Title != "" { //字符串
		updateField = append(updateField, t.Title)
	}
	if req.Content != "" { //字符串
		updateField = append(updateField, t.Content)
	}
	if req.SetingId != 0 { //整数
		updateField = append(updateField, t.SetingId)
	}
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}

	if !HasPrimaryKey {
		logger.Error("UpdateSysAppEntry error : Missing condition")
		return nil, errors.New("Missing condition")
	}

	dbObj := convert.SysAppEntry_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req, err
}

// //根据主键更新所有字段SysAppEntry
func (s *SysAppEntrySvc) UpdateAllSysAppEntry(req *proto.SysAppEntry) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数
	//要更新的字段,不包括主键
	var updateField []field.Expr

	updateField = append(updateField, t.Lang)
	updateField = append(updateField, t.Title)
	updateField = append(updateField, t.Content)
	updateField = append(updateField, t.SetingId)
	if len(updateField) > 0 {
		do = do.Select(updateField...)
	}
	//主键条件
	HasPrimaryKey := false
	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateAllSysAppEntry error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.SysAppEntry_pb2db(req)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateAllSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req, err
}

func (s *SysAppEntrySvc) UpdateFieldsSysAppEntry(req *proto.SysAppEntryUpdateFieldsRequest) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())

	var updateField []field.Expr
	for _, v := range req.Fields {
		col, ok := t.GetFieldByName(v)
		if ok {
			updateField = append(updateField, col)
		}
	}
	if len(updateField) == 0 {
		err := errors.New("UpdateFieldsSysAppEntry error : missing updateField")
		logger.Error(err)
		return nil, err
	}
	do = do.Select(updateField...)

	//主键条件
	HasPrimaryKey := false
	if req.Data.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Data.Id))
		HasPrimaryKey = true
	}
	if !HasPrimaryKey {
		logger.Error("UpdateFieldsSysAppEntry error : Missing condition")
		return nil, errors.New("Missing condition")
	}
	dbObj := convert.SysAppEntry_pb2db(req.Data)
	_, err := do.Updates(dbObj)
	if err != nil {
		logger.Errorf("UpdateFieldsSysAppEntry error : %s", err.Error())
		return nil, err
	}
	return req.Data, nil
}

// 根据非空条件查找SysAppEntry
func (s *SysAppEntrySvc) FindSysAppEntry(req *proto.SysAppEntryFilter) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	if req.Lang != "" { //字符串
		do = do.Where(t.Lang.Eq(req.Lang))
	}
	if req.Title != "" { //字符串
		do = do.Where(t.Title.Eq(req.Title))
	}
	if req.Content != "" { //字符串
		do = do.Where(t.Content.Eq(req.Content))
	}
	if req.SetingId != 0 { //整数
		do = do.Where(t.SetingId.Eq(req.SetingId))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindSysAppEntry error : %s", err.Error())
		return nil, err
	}
	res := convert.SysAppEntry_db2pb(dbObj)
	return res, err
}

// 根据数据库表主键查找SysAppEntry
func (s *SysAppEntrySvc) FindByIdSysAppEntry(req *proto.SysAppEntryFilter) (*proto.SysAppEntry, error) {
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	// fixme 请检查条件和校验参数

	if req.Id != 0 { //整数
		do = do.Where(t.Id.Eq(req.Id))
	}
	dbObj, err := do.First()
	if err != nil {
		logger.Errorf("FindByIdSysAppEntry error : %s", err.Error())
		return nil, err
	}
	res := convert.SysAppEntry_db2pb(dbObj)
	return res, err
}

// 根据分页条件查找SysAppEntry,请确保req.Query的结构字段与数据表model结构体字段保持一致，否则会有编译问题
func (s *SysAppEntrySvc) GetListSysAppEntry(req *proto.SysAppEntryListRequest) ([]*proto.SysAppEntry, int64, error) {
	// fixme 请检查条件和校验参数
	var err error
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	query := req.Query
	if query != nil {

		if query.Id != 0 { //整数
			do = do.Where(t.Id.Eq(query.Id))
		}
		if query.Lang != "" { //字符串
			do = do.Where(t.Lang.Like("%" + query.Lang + "%"))
		}
		if query.Title != "" { //字符串
			do = do.Where(t.Title.Like("%" + query.Title + "%"))
		}
		if query.Content != "" { //字符串
			do = do.Where(t.Content.Like("%" + query.Content + "%"))
		}
		if query.SetingId != 0 { //整数
			do = do.Where(t.SetingId.Eq(query.SetingId))
		}
	}
	orderCol, ok := t.GetFieldByName(req.OrderKey)
	if !ok {
		orderCol = t.Id
	}
	if req.OrderDesc != "" {
		do = do.Order(orderCol.Desc())
	} else {
		do = do.Order(orderCol)
	}

	var list []*model.TSysAppEntry
	var total int64
	if req.PageSize > 0 {
		limit := req.PageSize
		if req.Page == 0 {
			req.Page = 1
		}
		offset := req.PageSize * (req.Page - 1)
		list, total, err = do.FindByPage(int(offset), int(limit))
	} else {
		list, err = do.Find()
		total = int64(len(list))
	}
	if err != nil {
		logger.Errorf("GetListSysAppEntry error : %s", err.Error())
		return nil, 0, err
	}
	if len(list) == 0 {
		return nil, total, nil
	}
	result := make([]*proto.SysAppEntry, len(list))
	for i, v := range list {
		result[i] = convert.SysAppEntry_db2pb(v)
	}
	return result, total, nil
}

// 查询公版支持的语种.
func (s *SysAppEntrySvc) GetSupportedLangListDiy() ([]string, error) {

	var err error
	q := orm.Use(iotmodel.GetDB())
	tEntry := q.TSysAppEntry

	var list []*struct {
		Lang string `gorm:"column:lang" json:"lang"` // 设置id
	}
	err = tEntry.WithContext(context.Background()).Group(tEntry.Lang).Select(tEntry.Lang).Scan(&list)
	if err != nil {
		return nil, err
	}
	var rs = make([]string, 0)
	for _, v := range list {
		rs = append(rs, v.Lang)
	}
	return rs, nil
}

func (s *SysAppEntrySvc) GetListSysAppEntryListDiy(req *proto.SysAppEntryListDiyRequqest) ([]*proto.SysAppEntryDiy, int64, error) {
	// fixme 请检查条件和校验参数
	var err error
	q := orm.Use(iotmodel.GetDB())
	tSetting := q.TSysAppEntrySeting
	tDir := q.TSysAppDocDir
	tEntry := q.TSysAppEntry

	do := tSetting.WithContext(context.Background()).
		Join(tDir, tSetting.DirId.EqCol(tDir.Id)).
		Join(tEntry, tSetting.Id.EqCol(tEntry.SetingId))

	if req.DirId > 0 {
		//获取下级目录id
		var dirSvr = SysAppDocDirSvc{}
		ids, errIds := dirSvr.FindOemAppDocDirByIds(req.DirId)
		if errIds != nil {
			return nil, 0, errIds
		}
		do = do.Where(tDir.Id.In(ids...))
	}
	if req.IsEnable > 0 {
		do = do.Where(tSetting.IsEnable.Eq(req.IsEnable))
	}
	if req.IsNormal > 0 {
		do = do.Where(tSetting.IsNormal.Eq(req.IsNormal))
	}
	if req.Lang != "" {
		do = do.Where(tEntry.Lang.Eq(req.Lang))
	}
	if req.Title != "" {
		do = do.Where(tEntry.Title.Like("%" + req.Title + "%"))
	}

	do = do.Order(tSetting.Sort, tEntry.UpdatedAt.Desc())

	var list []*struct {
		SetingId int64 `gorm:"column:seting_id" json:"setingId"` // 设置id
		//DocId     int64                  `gorm:"column:doc_id" json:"docId"`                // 文档id
		DirId     int64     `gorm:"column:dir_id" json:"dirId"`       // 目录id
		Lang      string    `gorm:"column:lang" json:"lang"`          // 语种编码
		Title     string    `gorm:"column:title" json:"title"`        // 标题
		IsNormal  int32     `gorm:"column:is_normal" json:"isNormal"` // 是否常见
		IsEnable  int32     `gorm:"column:is_enable" json:"isEnable"` // 是否启用
		DirName   string    `gorm:"column:dir_name" json:"dirName"`   // 目录名称
		Sort      int64     `gorm:"column:sort" json:"sort"`
		UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"` // 更新时间
	}

	var total int64
	if req.PageSize <= 0 {
		req.PageSize = 10
	}

	limit := req.PageSize
	if req.Page == 0 {
		req.Page = 1
	}
	offset := req.PageSize * (req.Page - 1)
	total, err = do.Select(
		tSetting.Id.As("seting_id"), tEntry.Title, tDir.DirName, tSetting.IsEnable, tSetting.IsNormal, tEntry.UpdatedAt, tEntry.Lang, tDir.Id.As("dir_id"), tSetting.Sort,
	).ScanByPage(&list, int(offset), int(limit))

	if err != nil {
		logger.Errorf("GetListOemAppEntry error : %s", err.Error())
		return nil, 0, err
	}
	if len(list) == 0 {
		return nil, total, nil
	}

	var rsList = make([]*proto.SysAppEntryDiy, 0)

	for _, v := range list {
		rsList = append(rsList, &proto.SysAppEntryDiy{
			SetingId: v.SetingId,
			//DocId: v.DocId,
			DirId:     v.DirId,
			Lang:      v.Lang,
			Title:     v.Title,
			IsNormal:  v.IsNormal,
			IsEnable:  v.IsEnable,
			DirName:   v.DirName,
			Sort:      v.Sort,
			UpdatedAt: timestamppb.New(v.UpdatedAt),
		})
	}
	return rsList, total, nil
}

// 创建CreateSysAppEntryBatch
func (s *SysAppEntrySvc) CreateSysAppEntryBatch(req *proto.SysAppEntryBatchRequest) (*proto.SysAppEntryBatchRequest, error) {
	// fixme 请在这里校验参数
	t := orm.Use(iotmodel.GetDB()).TSysAppEntry
	do := t.WithContext(context.Background())
	reqBatch := make([]*model.TSysAppEntry, 0)
	for i := range req.SysAppEntrys {
		reqBatch = append(reqBatch, convert.SysAppEntry_pb2db(req.SysAppEntrys[i]))
	}
	err := do.CreateInBatches(reqBatch, len(reqBatch))
	if err != nil {
		logger.Errorf("CreateSysAppEntryBatch error : %s", err.Error())
		return nil, err
	}
	return req, err
}
