// Code generated by sgen.exe,2023-01-04 17:12:13. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package convert

import (
	"cloud_platform/iot_model/db_product/model"
	proto "cloud_platform/iot_proto/protos/protosService"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func OpmProductManual_pb2db(src *proto.OpmProductManual) *model.TOpmProductManual {
	if src == nil {
		return nil
	}
	dbObj := model.TOpmProductManual{
		Id:         src.Id,
		TenantId:   src.TenantId,
		ProductKey: src.ProductKey,
		FileName:   src.FileName,
		FileUrl:    src.FileUrl,
		FileMd5:    src.FileMd5,
		CreatedBy:  src.CreatedBy,
		CreatedAt:  src.CreatedAt.AsTime(),
		UpdatedBy:  src.UpdatedBy,
		UpdatedAt:  src.UpdatedAt.AsTime(),
	}
	return &dbObj
}

func OpmProductManual_db2pb(src *model.TOpmProductManual) *proto.OpmProductManual {
	if src == nil {
		return nil
	}
	pbObj := proto.OpmProductManual{
		Id:         src.Id,
		TenantId:   src.TenantId,
		ProductKey: src.ProductKey,
		FileName:   src.FileName,
		FileUrl:    src.FileUrl,
		FileMd5:    src.FileMd5,
		CreatedBy:  src.CreatedBy,
		CreatedAt:  timestamppb.New(src.CreatedAt),
		UpdatedBy:  src.UpdatedBy,
		UpdatedAt:  timestamppb.New(src.UpdatedAt),
	}
	return &pbObj
}
