// Code generated by sgen,2023-09-27 11:39:53. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package convert

import (
	"cloud_platform/iot_model/db_product/model"
	proto "cloud_platform/iot_proto/protos/protosService"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func OpmDocuments_pb2db(src *proto.OpmDocuments) *model.TOpmDocuments {
	if src == nil {
		return nil
	}
	dbObj := model.TOpmDocuments{
		Id:         src.Id,
		DataOrigin: src.DataOrigin,
		OriginId:   src.OriginId,
		OriginKey:  src.OriginKey,
		DocCode:    src.DocCode,
		DocName:    src.DocName,
		Remark:     src.Remark,
		FilePath:   src.FilePath,
		FileName:   src.FileName,
		FileSize:   src.FileSize,
		FileKey:    src.FileKey,
	}
	return &dbObj
}

func OpmDocuments_db2pb(src *model.TOpmDocuments) *proto.OpmDocuments {
	if src == nil {
		return nil
	}
	pbObj := proto.OpmDocuments{
		Id:         src.Id,
		DataOrigin: src.DataOrigin,
		OriginId:   src.OriginId,
		OriginKey:  src.OriginKey,
		DocCode:    src.DocCode,
		DocName:    src.DocName,
		Remark:     src.Remark,
		FilePath:   src.FilePath,
		FileName:   src.FileName,
		FileSize:   src.FileSize,
		FileKey:    src.FileKey,
		CreatedBy:  src.CreatedBy,
		UpdatedBy:  src.UpdatedBy,
		CreatedAt:  timestamppb.New(src.CreatedAt),
		UpdatedAt:  timestamppb.New(src.UpdatedAt),
	}
	return &pbObj
}
