// Code generated by sgen.exe,2022-05-05 19:33:56. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package convert

import (
	"cloud_platform/iot_model/db_product/model"
	proto "cloud_platform/iot_proto/protos/protosService"

	"google.golang.org/protobuf/types/known/timestamppb"
)

func PmControlPanels_pb2db(src *proto.PmControlPanels) *model.TPmControlPanels {
	if src == nil {
		return nil
	}
	dbObj := model.TPmControlPanels{
		Id:            src.Id,
		Name:          src.Name,
		NameEn:        src.NameEn,
		Lang:          src.Lang,
		Desc:          src.Desc,
		Url:           src.Url,
		UrlName:       src.UrlName,
		PanelSize:     src.PanelSize,
		PanelKey:      src.PanelKey,
		PreviewName:   src.PreviewName,
		PreviewUrl:    src.PreviewUrl,
		PreviewSize:   src.PreviewSize,
		ProductTypeId: src.ProductTypeId,
		ProductId:     src.ProductId,
		LangFileName:  src.LangFileName,
		Status:        src.Status,
		CreatedBy:     src.CreatedBy,
		UpdatedBy:     src.UpdatedBy,
		Code:   src.Code,
		//CreatedAt:     src.CreatedAt.AsTime(),
		//UpdatedAt:     src.UpdatedAt.AsTime(),
	}
	return &dbObj
}

func PmControlPanels_db2pb(src *model.TPmControlPanels) *proto.PmControlPanels {
	if src == nil {
		return nil
	}
	pbObj := proto.PmControlPanels{
		Id:            src.Id,
		Name:          src.Name,
		NameEn:        src.NameEn,
		Lang:          src.Lang,
		Desc:          src.Desc,
		Url:           src.Url,
		UrlName:       src.UrlName,
		PanelSize:     src.PanelSize,
		PanelKey:      src.PanelKey,
		PreviewName:   src.PreviewName,
		PreviewUrl:    src.PreviewUrl,
		PreviewSize:   src.PreviewSize,
		ProductTypeId: src.ProductTypeId,
		ProductId:     src.ProductId,
		LangFileName:  src.LangFileName,
		Status:        src.Status,
		CreatedBy:     src.CreatedBy,
		UpdatedBy:     src.UpdatedBy,
		CreatedAt:     timestamppb.New(src.CreatedAt),
		UpdatedAt:     timestamppb.New(src.UpdatedAt),
		Code:   src.Code,
	}
	return &pbObj
}

func OpmProductRelationPanels_db2pb(panel *proto.PmControlPanels, src *model.TOpmProductPanelRelation) {
	if src == nil && panel == nil {
		return
	}
	//兼容处理
	if src.PanelUrl != "" {
		panel.Url = src.PanelUrl
		panel.PanelSize = src.PanelSize
		panel.PanelKey = src.PanelKey
		panel.PreviewName = src.PreviewName
		panel.PreviewUrl = src.PreviewUrl
		panel.ProductId = src.ProductId
		panel.CreatedBy = src.CreatedBy
		panel.AppPanelType = src.AppPanelType
	}
}
