// Code generated by sgen.exe,2022-05-31 10:02:23. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package handler

import (
	"context"

	"cloud_platform/iot_message_service/service"
	proto "cloud_platform/iot_proto/protos/protosService"
)

type MpMessageTemplateHandler struct{}

// 创建
func (h *MpMessageTemplateHandler) Create(ctx context.Context, req *proto.MpMessageTemplate, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.CreateMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 匹配多条件删除
func (h *MpMessageTemplateHandler) Delete(ctx context.Context, req *proto.MpMessageTemplate, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.DeleteMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 匹配ID删除
func (h *MpMessageTemplateHandler) DeleteById(ctx context.Context, req *proto.MpMessageTemplate, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.DeleteByIdMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键批量删除
func (h *MpMessageTemplateHandler) DeleteByIds(ctx context.Context, req *proto.MpMessageTemplateBatchDeleteRequest, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.DeleteByIdsMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 更新
func (h *MpMessageTemplateHandler) Update(ctx context.Context, req *proto.MpMessageTemplate, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.UpdateMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新所有字段
func (h *MpMessageTemplateHandler) UpdateAll(ctx context.Context, req *proto.MpMessageTemplate, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.UpdateAllMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新指定列
func (h *MpMessageTemplateHandler) UpdateFields(ctx context.Context, req *proto.MpMessageTemplateUpdateFieldsRequest, resp *proto.Response) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	_, err := s.UpdateFieldsMpMessageTemplate(req)
	SetResponse(resp, err)
	return nil
}

// 多条件查找，返回单条数据
func (h *MpMessageTemplateHandler) Find(ctx context.Context, req *proto.MpMessageTemplateFilter, resp *proto.MpMessageTemplateResponse) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	data, err := s.FindMpMessageTemplate(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 根据ID查找，返回单条数据
func (h *MpMessageTemplateHandler) FindById(ctx context.Context, req *proto.MpMessageTemplateFilter, resp *proto.MpMessageTemplateResponse) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	data, err := s.FindByIdMpMessageTemplate(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 查找，支持分页，可返回多条数据
func (h *MpMessageTemplateHandler) Lists(ctx context.Context, req *proto.MpMessageTemplateListRequest, resp *proto.MpMessageTemplateResponse) error {
	s := service.MpMessageTemplateSvc{Ctx: ctx}
	data, total, err := s.GetListMpMessageTemplate(req)
	h.SetPageResponse(resp, data, total, err)
	return nil
}

func (h *MpMessageTemplateHandler) SetResponse(resp *proto.MpMessageTemplateResponse, data *proto.MpMessageTemplate, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
		resp.Total = 0
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		if data != nil {
			resp.Total = 1
			resp.Data = append(resp.Data, data)
		}
	}
}

func (h *MpMessageTemplateHandler) SetPageResponse(resp *proto.MpMessageTemplateResponse, list []*proto.MpMessageTemplate, total int64, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		resp.Total = total
		resp.Data = list
	}
}
