// Code generated by sgen.exe,2022-04-18 19:12:10. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package handler

import (
	"context"

	proto "cloud_platform/iot_proto/protos/protosService"
	"cloud_platform/iot_system_service/service"
)

type SysRoleDeptHandler struct{}

// 创建
func (h *SysRoleDeptHandler) Create(ctx context.Context, req *proto.SysRoleDept, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.CreateSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 匹配多条件删除
func (h *SysRoleDeptHandler) Delete(ctx context.Context, req *proto.SysRoleDept, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.DeleteSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 匹配ID删除
func (h *SysRoleDeptHandler) DeleteById(ctx context.Context, req *proto.SysRoleDept, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.DeleteByIdSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键批量删除
func (h *SysRoleDeptHandler) DeleteByIds(ctx context.Context, req *proto.SysRoleDeptBatchDeleteRequest, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.DeleteByIdsSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 更新
func (h *SysRoleDeptHandler) Update(ctx context.Context, req *proto.SysRoleDept, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.UpdateSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新所有字段
func (h *SysRoleDeptHandler) UpdateAll(ctx context.Context, req *proto.SysRoleDept, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.UpdateAllSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新指定列
func (h *SysRoleDeptHandler) UpdateFields(ctx context.Context, req *proto.SysRoleDeptUpdateFieldsRequest, resp *proto.Response) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	_, err := s.UpdateFieldsSysRoleDept(req)
	SetResponse(resp, err)
	return nil
}

// 多条件查找，返回单条数据
func (h *SysRoleDeptHandler) Find(ctx context.Context, req *proto.SysRoleDeptFilter, resp *proto.SysRoleDeptResponse) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	data, err := s.FindSysRoleDept(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 根据ID查找，返回单条数据
func (h *SysRoleDeptHandler) FindById(ctx context.Context, req *proto.SysRoleDeptFilter, resp *proto.SysRoleDeptResponse) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	data, err := s.FindByIdSysRoleDept(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 查找，支持分页，可返回多条数据
func (h *SysRoleDeptHandler) Lists(ctx context.Context, req *proto.SysRoleDeptListRequest, resp *proto.SysRoleDeptResponse) error {
	s := service.SysRoleDeptSvc{Ctx: ctx}
	data, total, err := s.GetListSysRoleDept(req)
	h.SetPageResponse(resp, data, total, err)
	return nil
}

func (h *SysRoleDeptHandler) SetResponse(resp *proto.SysRoleDeptResponse, data *proto.SysRoleDept, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
		resp.Total = 0
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		if data != nil {
			resp.Total = 1
			resp.Data = append(resp.Data, data)
		}
	}
}

func (h *SysRoleDeptHandler) SetPageResponse(resp *proto.SysRoleDeptResponse, list []*proto.SysRoleDept, total int64, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		resp.Total = total
		resp.Data = list
	}
}
