// Code generated by sgen.exe,2022-04-18 19:12:08. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package handler

import (
	"context"

	proto "cloud_platform/iot_proto/protos/protosService"
	"cloud_platform/iot_system_service/service"
)

type SysCasbinRuleHandler struct{}

// 创建
func (h *SysCasbinRuleHandler) Create(ctx context.Context, req *proto.SysCasbinRule, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.CreateSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 匹配多条件删除
func (h *SysCasbinRuleHandler) Delete(ctx context.Context, req *proto.SysCasbinRule, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.DeleteSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 匹配ID删除
func (h *SysCasbinRuleHandler) DeleteById(ctx context.Context, req *proto.SysCasbinRule, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.DeleteByIdSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键批量删除
func (h *SysCasbinRuleHandler) DeleteByIds(ctx context.Context, req *proto.SysCasbinRuleBatchDeleteRequest, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.DeleteByIdsSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 更新
func (h *SysCasbinRuleHandler) Update(ctx context.Context, req *proto.SysCasbinRule, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.UpdateSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新所有字段
func (h *SysCasbinRuleHandler) UpdateAll(ctx context.Context, req *proto.SysCasbinRule, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.UpdateAllSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新指定列
func (h *SysCasbinRuleHandler) UpdateFields(ctx context.Context, req *proto.SysCasbinRuleUpdateFieldsRequest, resp *proto.Response) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	_, err := s.UpdateFieldsSysCasbinRule(req)
	SetResponse(resp, err)
	return nil
}

// 多条件查找，返回单条数据
func (h *SysCasbinRuleHandler) Find(ctx context.Context, req *proto.SysCasbinRuleFilter, resp *proto.SysCasbinRuleResponse) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	data, err := s.FindSysCasbinRule(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 根据ID查找，返回单条数据
func (h *SysCasbinRuleHandler) FindById(ctx context.Context, req *proto.SysCasbinRuleFilter, resp *proto.SysCasbinRuleResponse) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	data, err := s.FindByIdSysCasbinRule(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 查找，支持分页，可返回多条数据
func (h *SysCasbinRuleHandler) Lists(ctx context.Context, req *proto.SysCasbinRuleListRequest, resp *proto.SysCasbinRuleResponse) error {
	s := service.SysCasbinRuleSvc{Ctx: ctx}
	data, total, err := s.GetListSysCasbinRule(req)
	h.SetPageResponse(resp, data, total, err)
	return nil
}

func (h *SysCasbinRuleHandler) SetResponse(resp *proto.SysCasbinRuleResponse, data *proto.SysCasbinRule, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
		resp.Total = 0
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		if data != nil {
			resp.Total = 1
			resp.Data = append(resp.Data, data)
		}
	}
}

func (h *SysCasbinRuleHandler) SetPageResponse(resp *proto.SysCasbinRuleResponse, list []*proto.SysCasbinRule, total int64, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		resp.Total = total
		resp.Data = list
	}
}
