// Code generated by sgen.exe,2022-06-02 11:15:12. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

package handler

import (
	"context"

	"cloud_platform/iot_app_oem_service/service"
	proto "cloud_platform/iot_proto/protos/protosService"
)

type OemAppUiConfigHandler struct{}

// 创建
func (h *OemAppUiConfigHandler) Create(ctx context.Context, req *proto.OemAppUiConfig, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.CreateOemAppUiConfig(req)
	SetResponse(resp, err)
	resp.Data = req.Id
	return nil
}

// 匹配多条件删除
func (h *OemAppUiConfigHandler) Delete(ctx context.Context, req *proto.OemAppUiConfig, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.DeleteOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 匹配ID删除
func (h *OemAppUiConfigHandler) DeleteById(ctx context.Context, req *proto.OemAppUiConfig, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.DeleteByIdOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键批量删除
func (h *OemAppUiConfigHandler) DeleteByIds(ctx context.Context, req *proto.OemAppUiConfigBatchDeleteRequest, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.DeleteByIdsOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 更新
func (h *OemAppUiConfigHandler) Update(ctx context.Context, req *proto.OemAppUiConfig, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.UpdateOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新所有字段
func (h *OemAppUiConfigHandler) UpdateAll(ctx context.Context, req *proto.OemAppUiConfig, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.UpdateAllOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 根据主键更新指定列
func (h *OemAppUiConfigHandler) UpdateFields(ctx context.Context, req *proto.OemAppUiConfigUpdateFieldsRequest, resp *proto.Response) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	_, err := s.UpdateFieldsOemAppUiConfig(req)
	SetResponse(resp, err)
	return nil
}

// 多条件查找，返回单条数据
func (h *OemAppUiConfigHandler) Find(ctx context.Context, req *proto.OemAppUiConfigFilter, resp *proto.OemAppUiConfigResponse) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	data, err := s.FindOemAppUiConfig(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 根据ID查找，返回单条数据
func (h *OemAppUiConfigHandler) FindById(ctx context.Context, req *proto.OemAppUiConfigFilter, resp *proto.OemAppUiConfigResponse) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	data, err := s.FindByIdOemAppUiConfig(req)
	h.SetResponse(resp, data, err)
	return nil
}

// 查找，支持分页，可返回多条数据
func (h *OemAppUiConfigHandler) Lists(ctx context.Context, req *proto.OemAppUiConfigListRequest, resp *proto.OemAppUiConfigResponse) error {
	s := service.OemAppUiConfigSvc{Ctx: ctx}
	data, total, err := s.GetListOemAppUiConfig(req)
	h.SetPageResponse(resp, data, total, err)
	return nil
}

func (h *OemAppUiConfigHandler) SetResponse(resp *proto.OemAppUiConfigResponse, data *proto.OemAppUiConfig, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
		resp.Total = 0
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		if data != nil {
			resp.Total = 1
			resp.Data = append(resp.Data, data)
		}
	}
}

func (h *OemAppUiConfigHandler) SetPageResponse(resp *proto.OemAppUiConfigResponse, list []*proto.OemAppUiConfig, total int64, err error) {
	if err != nil {
		resp.Code = ERROR
		resp.Message = err.Error()
	} else {
		resp.Code = SUCCESS
		resp.Message = "success"
		resp.Total = total
		resp.Data = list
	}
}
