// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTPmThingModelProperties = "t_pm_thing_model_properties"

// TPmThingModelProperties mapped from table <t_pm_thing_model_properties>
type TPmThingModelProperties struct {
	Id            int64          `gorm:"column:id;primaryKey" json:"id"`                        // 主键（雪花算法19位）
	ModelId       int64          `gorm:"column:model_id;not null" json:"modelId"`               // 物模型ID(t_pm_thing_model.id)
	ProductKey    string         `gorm:"column:product_key" json:"productKey"`                  // 产品唯一标识
	Identifier    string         `gorm:"column:identifier;not null" json:"identifier"`          // 属性的标识符。可包含大小写英文字母、数字、下划线（_），长度不超过50个字符。
	DataType      string         `gorm:"column:data_type;not null" json:"dataType"`             // 属性值的数据类型。可选值：ARRAY、STRUCT、INT、FLOAT、DOUBLE、TEXT、DATE、JSON、ENUM、BOOL。不同数据类型，可传入的参数不同。
	Name          string         `gorm:"column:name;not null" json:"name"`                      // 属性名称。可包含中文、大小写英文字母、数字、短划线（-）、下划线（_）和半角句号（.），且必须以中文、英文字母或数字开头，长度不超过30个字符，一个中文计为一个字符。
	RwFlag        string         `gorm:"column:rw_flag;not null" json:"rwFlag"`                 // 在云端可以对该属性进行的操作类型。READ_WRITE：读写。READ_ONLY：只读。WRITE_ONLY：只写。
	DataSpecs     string         `gorm:"column:data_specs" json:"dataSpecs"`                    // 数据类型（dataType）为非列表型（INT、FLOAT、DOUBLE、TEXT、DATE、ARRAY）的数据规范存储在dataSpecs中
	DataSpecsList string         `gorm:"column:data_specs_list" json:"dataSpecsList"`           // 数据类型（dataType）为列表型（ENUM、BOOL、STRUCT）的数据规范存储在dataSpecsList中
	Required      int32          `gorm:"column:required;not null;default:0" json:"required"`    // 是否是标准品类的必选属性。1：是, 0：否
	Custom        int32          `gorm:"column:custom;not null;default:0" json:"custom"`        // 是否是自定义功能。1：是, 0：否
	Extension     string         `gorm:"column:extension" json:"extension"`                     // 扩展字段
	Desc          string         `gorm:"column:desc" json:"desc"`                               // 功能描述
	TriggerCond   int32          `gorm:"column:trigger_cond" json:"triggerCond"`                // 触发条件
	ExecCond      int32          `gorm:"column:exec_cond" json:"execCond"`                      // 执行条件
	CreatedBy     int64          `gorm:"column:created_by;not null;default:0" json:"createdBy"` // 创建人
	CreatedAt     time.Time      `gorm:"column:created_at" json:"createdAt"`                    // 创建时间
	UpdatedBy     int64          `gorm:"column:updated_by;not null;default:0" json:"updatedBy"` // 修改人
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updatedAt"`                    // 修改时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                    // 删除时间
	StdId         int64          `gorm:"column:std_id" json:"stdId"`
	Valid         int32          `gorm:"column:valid;default:0" json:"valid"`
	Dpid          int32          `gorm:"column:dpid" json:"dpid"` // dpid
}

// TableName TPmThingModelProperties's table name
func (*TPmThingModelProperties) TableName() string {
	return TableNameTPmThingModelProperties
}
