// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: data_overview_hour_service.gen.proto

package protosService

import (
	
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for DataOverviewHourService service

func NewDataOverviewHourServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "DataOverviewHourService.Create",
			Path:    []string{"/v1/dataOverviewHour/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.Delete",
			Path:    []string{"/v1/dataOverviewHour/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.DeleteById",
			Path:    []string{"/v1/dataOverviewHour/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.DeleteByIds",
			Path:    []string{"/v1/dataOverviewHour/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.Update",
			Path:    []string{"/v1/dataOverviewHour/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.UpdateAll",
			Path:    []string{"/v1/dataOverviewHour/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.UpdateFields",
			Path:    []string{"/v1/dataOverviewHour/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.FindById",
			Path:    []string{"/v1/dataOverviewHour/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.Find",
			Path:    []string{"/v1/dataOverviewHour/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "DataOverviewHourService.Lists",
			Path:    []string{"/v1/dataOverviewHour/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for DataOverviewHourService service

type DataOverviewHourService interface {
	//创建
	Create(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *DataOverviewHourBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *DataOverviewHourUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *DataOverviewHourFilter, opts ...client.CallOption) (*DataOverviewHourResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *DataOverviewHourFilter, opts ...client.CallOption) (*DataOverviewHourResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *DataOverviewHourListRequest, opts ...client.CallOption) (*DataOverviewHourResponse, error)
}

type dataOverviewHourService struct {
	c    client.Client
	name string
}

func NewDataOverviewHourService(name string, c client.Client) DataOverviewHourService {
	return &dataOverviewHourService{
		c:    c,
		name: name,
	}
}

func (c *dataOverviewHourService) Create(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) Delete(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) DeleteById(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) DeleteByIds(ctx context.Context, in *DataOverviewHourBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) Update(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) UpdateAll(ctx context.Context, in *DataOverviewHour, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) UpdateFields(ctx context.Context, in *DataOverviewHourUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) FindById(ctx context.Context, in *DataOverviewHourFilter, opts ...client.CallOption) (*DataOverviewHourResponse, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.FindById", in)
	out := new(DataOverviewHourResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) Find(ctx context.Context, in *DataOverviewHourFilter, opts ...client.CallOption) (*DataOverviewHourResponse, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.Find", in)
	out := new(DataOverviewHourResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataOverviewHourService) Lists(ctx context.Context, in *DataOverviewHourListRequest, opts ...client.CallOption) (*DataOverviewHourResponse, error) {
	req := c.c.NewRequest(c.name, "DataOverviewHourService.Lists", in)
	out := new(DataOverviewHourResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataOverviewHourService service

type DataOverviewHourServiceHandler interface {
	//创建
	Create(context.Context, *DataOverviewHour, *Response) error
	//匹配多条件删除
	Delete(context.Context, *DataOverviewHour, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *DataOverviewHour, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *DataOverviewHourBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *DataOverviewHour, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *DataOverviewHour, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *DataOverviewHourUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *DataOverviewHourFilter, *DataOverviewHourResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *DataOverviewHourFilter, *DataOverviewHourResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *DataOverviewHourListRequest, *DataOverviewHourResponse) error
}

func RegisterDataOverviewHourServiceHandler(s server.Server, hdlr DataOverviewHourServiceHandler, opts ...server.HandlerOption) error {
	type dataOverviewHourService interface {
		Create(ctx context.Context, in *DataOverviewHour, out *Response) error
		Delete(ctx context.Context, in *DataOverviewHour, out *Response) error
		DeleteById(ctx context.Context, in *DataOverviewHour, out *Response) error
		DeleteByIds(ctx context.Context, in *DataOverviewHourBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *DataOverviewHour, out *Response) error
		UpdateAll(ctx context.Context, in *DataOverviewHour, out *Response) error
		UpdateFields(ctx context.Context, in *DataOverviewHourUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *DataOverviewHourFilter, out *DataOverviewHourResponse) error
		Find(ctx context.Context, in *DataOverviewHourFilter, out *DataOverviewHourResponse) error
		Lists(ctx context.Context, in *DataOverviewHourListRequest, out *DataOverviewHourResponse) error
	}
	type DataOverviewHourService struct {
		dataOverviewHourService
	}
	h := &dataOverviewHourServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.Create",
		Path:    []string{"/v1/dataOverviewHour/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.Delete",
		Path:    []string{"/v1/dataOverviewHour/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.DeleteById",
		Path:    []string{"/v1/dataOverviewHour/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.DeleteByIds",
		Path:    []string{"/v1/dataOverviewHour/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.Update",
		Path:    []string{"/v1/dataOverviewHour/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.UpdateAll",
		Path:    []string{"/v1/dataOverviewHour/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.UpdateFields",
		Path:    []string{"/v1/dataOverviewHour/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.FindById",
		Path:    []string{"/v1/dataOverviewHour/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.Find",
		Path:    []string{"/v1/dataOverviewHour/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "DataOverviewHourService.Lists",
		Path:    []string{"/v1/dataOverviewHour/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&DataOverviewHourService{h}, opts...))
}

type dataOverviewHourServiceHandler struct {
	DataOverviewHourServiceHandler
}

func (h *dataOverviewHourServiceHandler) Create(ctx context.Context, in *DataOverviewHour, out *Response) error {
	return h.DataOverviewHourServiceHandler.Create(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) Delete(ctx context.Context, in *DataOverviewHour, out *Response) error {
	return h.DataOverviewHourServiceHandler.Delete(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) DeleteById(ctx context.Context, in *DataOverviewHour, out *Response) error {
	return h.DataOverviewHourServiceHandler.DeleteById(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) DeleteByIds(ctx context.Context, in *DataOverviewHourBatchDeleteRequest, out *Response) error {
	return h.DataOverviewHourServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) Update(ctx context.Context, in *DataOverviewHour, out *Response) error {
	return h.DataOverviewHourServiceHandler.Update(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) UpdateAll(ctx context.Context, in *DataOverviewHour, out *Response) error {
	return h.DataOverviewHourServiceHandler.UpdateAll(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) UpdateFields(ctx context.Context, in *DataOverviewHourUpdateFieldsRequest, out *Response) error {
	return h.DataOverviewHourServiceHandler.UpdateFields(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) FindById(ctx context.Context, in *DataOverviewHourFilter, out *DataOverviewHourResponse) error {
	return h.DataOverviewHourServiceHandler.FindById(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) Find(ctx context.Context, in *DataOverviewHourFilter, out *DataOverviewHourResponse) error {
	return h.DataOverviewHourServiceHandler.Find(ctx, in, out)
}

func (h *dataOverviewHourServiceHandler) Lists(ctx context.Context, in *DataOverviewHourListRequest, out *DataOverviewHourResponse) error {
	return h.DataOverviewHourServiceHandler.Lists(ctx, in, out)
}
