// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: iot_ota_white_service.gen.proto

package protosService

import (
	
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for IotOtaWhiteService service

func NewIotOtaWhiteServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "IotOtaWhiteService.Create",
			Path:    []string{"/v1/iotOtaWhite/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.Delete",
			Path:    []string{"/v1/iotOtaWhite/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.DeleteById",
			Path:    []string{"/v1/iotOtaWhite/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.DeleteByIds",
			Path:    []string{"/v1/iotOtaWhite/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.Update",
			Path:    []string{"/v1/iotOtaWhite/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.UpdateAll",
			Path:    []string{"/v1/iotOtaWhite/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.UpdateFields",
			Path:    []string{"/v1/iotOtaWhite/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.FindById",
			Path:    []string{"/v1/iotOtaWhite/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.Find",
			Path:    []string{"/v1/iotOtaWhite/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "IotOtaWhiteService.Lists",
			Path:    []string{"/v1/iotOtaWhite/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for IotOtaWhiteService service

type IotOtaWhiteService interface {
	//创建
	Create(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *IotOtaWhiteBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *IotOtaWhiteUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *IotOtaWhiteFilter, opts ...client.CallOption) (*IotOtaWhiteResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *IotOtaWhiteFilter, opts ...client.CallOption) (*IotOtaWhiteResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *IotOtaWhiteListRequest, opts ...client.CallOption) (*IotOtaWhiteResponse, error)
}

type iotOtaWhiteService struct {
	c    client.Client
	name string
}

func NewIotOtaWhiteService(name string, c client.Client) IotOtaWhiteService {
	return &iotOtaWhiteService{
		c:    c,
		name: name,
	}
}

func (c *iotOtaWhiteService) Create(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) Delete(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) DeleteById(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) DeleteByIds(ctx context.Context, in *IotOtaWhiteBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) Update(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) UpdateAll(ctx context.Context, in *IotOtaWhite, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) UpdateFields(ctx context.Context, in *IotOtaWhiteUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) FindById(ctx context.Context, in *IotOtaWhiteFilter, opts ...client.CallOption) (*IotOtaWhiteResponse, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.FindById", in)
	out := new(IotOtaWhiteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) Find(ctx context.Context, in *IotOtaWhiteFilter, opts ...client.CallOption) (*IotOtaWhiteResponse, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.Find", in)
	out := new(IotOtaWhiteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iotOtaWhiteService) Lists(ctx context.Context, in *IotOtaWhiteListRequest, opts ...client.CallOption) (*IotOtaWhiteResponse, error) {
	req := c.c.NewRequest(c.name, "IotOtaWhiteService.Lists", in)
	out := new(IotOtaWhiteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IotOtaWhiteService service

type IotOtaWhiteServiceHandler interface {
	//创建
	Create(context.Context, *IotOtaWhite, *Response) error
	//匹配多条件删除
	Delete(context.Context, *IotOtaWhite, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *IotOtaWhite, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *IotOtaWhiteBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *IotOtaWhite, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *IotOtaWhite, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *IotOtaWhiteUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *IotOtaWhiteFilter, *IotOtaWhiteResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *IotOtaWhiteFilter, *IotOtaWhiteResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *IotOtaWhiteListRequest, *IotOtaWhiteResponse) error
}

func RegisterIotOtaWhiteServiceHandler(s server.Server, hdlr IotOtaWhiteServiceHandler, opts ...server.HandlerOption) error {
	type iotOtaWhiteService interface {
		Create(ctx context.Context, in *IotOtaWhite, out *Response) error
		Delete(ctx context.Context, in *IotOtaWhite, out *Response) error
		DeleteById(ctx context.Context, in *IotOtaWhite, out *Response) error
		DeleteByIds(ctx context.Context, in *IotOtaWhiteBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *IotOtaWhite, out *Response) error
		UpdateAll(ctx context.Context, in *IotOtaWhite, out *Response) error
		UpdateFields(ctx context.Context, in *IotOtaWhiteUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *IotOtaWhiteFilter, out *IotOtaWhiteResponse) error
		Find(ctx context.Context, in *IotOtaWhiteFilter, out *IotOtaWhiteResponse) error
		Lists(ctx context.Context, in *IotOtaWhiteListRequest, out *IotOtaWhiteResponse) error
	}
	type IotOtaWhiteService struct {
		iotOtaWhiteService
	}
	h := &iotOtaWhiteServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.Create",
		Path:    []string{"/v1/iotOtaWhite/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.Delete",
		Path:    []string{"/v1/iotOtaWhite/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.DeleteById",
		Path:    []string{"/v1/iotOtaWhite/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.DeleteByIds",
		Path:    []string{"/v1/iotOtaWhite/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.Update",
		Path:    []string{"/v1/iotOtaWhite/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.UpdateAll",
		Path:    []string{"/v1/iotOtaWhite/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.UpdateFields",
		Path:    []string{"/v1/iotOtaWhite/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.FindById",
		Path:    []string{"/v1/iotOtaWhite/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.Find",
		Path:    []string{"/v1/iotOtaWhite/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "IotOtaWhiteService.Lists",
		Path:    []string{"/v1/iotOtaWhite/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&IotOtaWhiteService{h}, opts...))
}

type iotOtaWhiteServiceHandler struct {
	IotOtaWhiteServiceHandler
}

func (h *iotOtaWhiteServiceHandler) Create(ctx context.Context, in *IotOtaWhite, out *Response) error {
	return h.IotOtaWhiteServiceHandler.Create(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) Delete(ctx context.Context, in *IotOtaWhite, out *Response) error {
	return h.IotOtaWhiteServiceHandler.Delete(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) DeleteById(ctx context.Context, in *IotOtaWhite, out *Response) error {
	return h.IotOtaWhiteServiceHandler.DeleteById(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) DeleteByIds(ctx context.Context, in *IotOtaWhiteBatchDeleteRequest, out *Response) error {
	return h.IotOtaWhiteServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) Update(ctx context.Context, in *IotOtaWhite, out *Response) error {
	return h.IotOtaWhiteServiceHandler.Update(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) UpdateAll(ctx context.Context, in *IotOtaWhite, out *Response) error {
	return h.IotOtaWhiteServiceHandler.UpdateAll(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) UpdateFields(ctx context.Context, in *IotOtaWhiteUpdateFieldsRequest, out *Response) error {
	return h.IotOtaWhiteServiceHandler.UpdateFields(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) FindById(ctx context.Context, in *IotOtaWhiteFilter, out *IotOtaWhiteResponse) error {
	return h.IotOtaWhiteServiceHandler.FindById(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) Find(ctx context.Context, in *IotOtaWhiteFilter, out *IotOtaWhiteResponse) error {
	return h.IotOtaWhiteServiceHandler.Find(ctx, in, out)
}

func (h *iotOtaWhiteServiceHandler) Lists(ctx context.Context, in *IotOtaWhiteListRequest, out *IotOtaWhiteResponse) error {
	return h.IotOtaWhiteServiceHandler.Lists(ctx, in, out)
}
