// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: open_user_online_service.gen.proto

package protosService

import (
	
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for OpenUserOnlineService service

func NewOpenUserOnlineServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "OpenUserOnlineService.Create",
			Path:    []string{"/v1/openUserOnline/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.Delete",
			Path:    []string{"/v1/openUserOnline/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.DeleteById",
			Path:    []string{"/v1/openUserOnline/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.DeleteByIds",
			Path:    []string{"/v1/openUserOnline/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.Update",
			Path:    []string{"/v1/openUserOnline/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.UpdateAll",
			Path:    []string{"/v1/openUserOnline/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.UpdateFields",
			Path:    []string{"/v1/openUserOnline/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.FindById",
			Path:    []string{"/v1/openUserOnline/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.Find",
			Path:    []string{"/v1/openUserOnline/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "OpenUserOnlineService.Lists",
			Path:    []string{"/v1/openUserOnline/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for OpenUserOnlineService service

type OpenUserOnlineService interface {
	//创建
	Create(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *OpenUserOnlineBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *OpenUserOnlineUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *OpenUserOnlineFilter, opts ...client.CallOption) (*OpenUserOnlineResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *OpenUserOnlineFilter, opts ...client.CallOption) (*OpenUserOnlineResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *OpenUserOnlineListRequest, opts ...client.CallOption) (*OpenUserOnlineResponse, error)
}

type openUserOnlineService struct {
	c    client.Client
	name string
}

func NewOpenUserOnlineService(name string, c client.Client) OpenUserOnlineService {
	return &openUserOnlineService{
		c:    c,
		name: name,
	}
}

func (c *openUserOnlineService) Create(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) Delete(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) DeleteById(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) DeleteByIds(ctx context.Context, in *OpenUserOnlineBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) Update(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) UpdateAll(ctx context.Context, in *OpenUserOnline, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) UpdateFields(ctx context.Context, in *OpenUserOnlineUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) FindById(ctx context.Context, in *OpenUserOnlineFilter, opts ...client.CallOption) (*OpenUserOnlineResponse, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.FindById", in)
	out := new(OpenUserOnlineResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) Find(ctx context.Context, in *OpenUserOnlineFilter, opts ...client.CallOption) (*OpenUserOnlineResponse, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.Find", in)
	out := new(OpenUserOnlineResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openUserOnlineService) Lists(ctx context.Context, in *OpenUserOnlineListRequest, opts ...client.CallOption) (*OpenUserOnlineResponse, error) {
	req := c.c.NewRequest(c.name, "OpenUserOnlineService.Lists", in)
	out := new(OpenUserOnlineResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OpenUserOnlineService service

type OpenUserOnlineServiceHandler interface {
	//创建
	Create(context.Context, *OpenUserOnline, *Response) error
	//匹配多条件删除
	Delete(context.Context, *OpenUserOnline, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *OpenUserOnline, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *OpenUserOnlineBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *OpenUserOnline, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *OpenUserOnline, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *OpenUserOnlineUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *OpenUserOnlineFilter, *OpenUserOnlineResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *OpenUserOnlineFilter, *OpenUserOnlineResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *OpenUserOnlineListRequest, *OpenUserOnlineResponse) error
}

func RegisterOpenUserOnlineServiceHandler(s server.Server, hdlr OpenUserOnlineServiceHandler, opts ...server.HandlerOption) error {
	type openUserOnlineService interface {
		Create(ctx context.Context, in *OpenUserOnline, out *Response) error
		Delete(ctx context.Context, in *OpenUserOnline, out *Response) error
		DeleteById(ctx context.Context, in *OpenUserOnline, out *Response) error
		DeleteByIds(ctx context.Context, in *OpenUserOnlineBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *OpenUserOnline, out *Response) error
		UpdateAll(ctx context.Context, in *OpenUserOnline, out *Response) error
		UpdateFields(ctx context.Context, in *OpenUserOnlineUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *OpenUserOnlineFilter, out *OpenUserOnlineResponse) error
		Find(ctx context.Context, in *OpenUserOnlineFilter, out *OpenUserOnlineResponse) error
		Lists(ctx context.Context, in *OpenUserOnlineListRequest, out *OpenUserOnlineResponse) error
	}
	type OpenUserOnlineService struct {
		openUserOnlineService
	}
	h := &openUserOnlineServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.Create",
		Path:    []string{"/v1/openUserOnline/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.Delete",
		Path:    []string{"/v1/openUserOnline/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.DeleteById",
		Path:    []string{"/v1/openUserOnline/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.DeleteByIds",
		Path:    []string{"/v1/openUserOnline/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.Update",
		Path:    []string{"/v1/openUserOnline/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.UpdateAll",
		Path:    []string{"/v1/openUserOnline/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.UpdateFields",
		Path:    []string{"/v1/openUserOnline/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.FindById",
		Path:    []string{"/v1/openUserOnline/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.Find",
		Path:    []string{"/v1/openUserOnline/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "OpenUserOnlineService.Lists",
		Path:    []string{"/v1/openUserOnline/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&OpenUserOnlineService{h}, opts...))
}

type openUserOnlineServiceHandler struct {
	OpenUserOnlineServiceHandler
}

func (h *openUserOnlineServiceHandler) Create(ctx context.Context, in *OpenUserOnline, out *Response) error {
	return h.OpenUserOnlineServiceHandler.Create(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) Delete(ctx context.Context, in *OpenUserOnline, out *Response) error {
	return h.OpenUserOnlineServiceHandler.Delete(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) DeleteById(ctx context.Context, in *OpenUserOnline, out *Response) error {
	return h.OpenUserOnlineServiceHandler.DeleteById(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) DeleteByIds(ctx context.Context, in *OpenUserOnlineBatchDeleteRequest, out *Response) error {
	return h.OpenUserOnlineServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) Update(ctx context.Context, in *OpenUserOnline, out *Response) error {
	return h.OpenUserOnlineServiceHandler.Update(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) UpdateAll(ctx context.Context, in *OpenUserOnline, out *Response) error {
	return h.OpenUserOnlineServiceHandler.UpdateAll(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) UpdateFields(ctx context.Context, in *OpenUserOnlineUpdateFieldsRequest, out *Response) error {
	return h.OpenUserOnlineServiceHandler.UpdateFields(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) FindById(ctx context.Context, in *OpenUserOnlineFilter, out *OpenUserOnlineResponse) error {
	return h.OpenUserOnlineServiceHandler.FindById(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) Find(ctx context.Context, in *OpenUserOnlineFilter, out *OpenUserOnlineResponse) error {
	return h.OpenUserOnlineServiceHandler.Find(ctx, in, out)
}

func (h *openUserOnlineServiceHandler) Lists(ctx context.Context, in *OpenUserOnlineListRequest, out *OpenUserOnlineResponse) error {
	return h.OpenUserOnlineServiceHandler.Lists(ctx, in, out)
}
