// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: plugins_manage_service.gen.proto

package protosService

import (
	
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PluginsManageService service

func NewPluginsManageServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "PluginsManageService.Create",
			Path:    []string{"/v1/pluginsManage/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.Delete",
			Path:    []string{"/v1/pluginsManage/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.DeleteById",
			Path:    []string{"/v1/pluginsManage/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.DeleteByIds",
			Path:    []string{"/v1/pluginsManage/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.Update",
			Path:    []string{"/v1/pluginsManage/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.UpdateAll",
			Path:    []string{"/v1/pluginsManage/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.UpdateFields",
			Path:    []string{"/v1/pluginsManage/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.FindById",
			Path:    []string{"/v1/pluginsManage/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.Find",
			Path:    []string{"/v1/pluginsManage/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PluginsManageService.Lists",
			Path:    []string{"/v1/pluginsManage/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for PluginsManageService service

type PluginsManageService interface {
	//创建
	Create(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *PluginsManageBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *PluginsManageUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *PluginsManageFilter, opts ...client.CallOption) (*PluginsManageResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *PluginsManageFilter, opts ...client.CallOption) (*PluginsManageResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *PluginsManageListRequest, opts ...client.CallOption) (*PluginsManageResponse, error)
}

type pluginsManageService struct {
	c    client.Client
	name string
}

func NewPluginsManageService(name string, c client.Client) PluginsManageService {
	return &pluginsManageService{
		c:    c,
		name: name,
	}
}

func (c *pluginsManageService) Create(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) Delete(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) DeleteById(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) DeleteByIds(ctx context.Context, in *PluginsManageBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) Update(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) UpdateAll(ctx context.Context, in *PluginsManage, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) UpdateFields(ctx context.Context, in *PluginsManageUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) FindById(ctx context.Context, in *PluginsManageFilter, opts ...client.CallOption) (*PluginsManageResponse, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.FindById", in)
	out := new(PluginsManageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) Find(ctx context.Context, in *PluginsManageFilter, opts ...client.CallOption) (*PluginsManageResponse, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.Find", in)
	out := new(PluginsManageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginsManageService) Lists(ctx context.Context, in *PluginsManageListRequest, opts ...client.CallOption) (*PluginsManageResponse, error) {
	req := c.c.NewRequest(c.name, "PluginsManageService.Lists", in)
	out := new(PluginsManageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PluginsManageService service

type PluginsManageServiceHandler interface {
	//创建
	Create(context.Context, *PluginsManage, *Response) error
	//匹配多条件删除
	Delete(context.Context, *PluginsManage, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *PluginsManage, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *PluginsManageBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *PluginsManage, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *PluginsManage, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *PluginsManageUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *PluginsManageFilter, *PluginsManageResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *PluginsManageFilter, *PluginsManageResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *PluginsManageListRequest, *PluginsManageResponse) error
}

func RegisterPluginsManageServiceHandler(s server.Server, hdlr PluginsManageServiceHandler, opts ...server.HandlerOption) error {
	type pluginsManageService interface {
		Create(ctx context.Context, in *PluginsManage, out *Response) error
		Delete(ctx context.Context, in *PluginsManage, out *Response) error
		DeleteById(ctx context.Context, in *PluginsManage, out *Response) error
		DeleteByIds(ctx context.Context, in *PluginsManageBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *PluginsManage, out *Response) error
		UpdateAll(ctx context.Context, in *PluginsManage, out *Response) error
		UpdateFields(ctx context.Context, in *PluginsManageUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *PluginsManageFilter, out *PluginsManageResponse) error
		Find(ctx context.Context, in *PluginsManageFilter, out *PluginsManageResponse) error
		Lists(ctx context.Context, in *PluginsManageListRequest, out *PluginsManageResponse) error
	}
	type PluginsManageService struct {
		pluginsManageService
	}
	h := &pluginsManageServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.Create",
		Path:    []string{"/v1/pluginsManage/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.Delete",
		Path:    []string{"/v1/pluginsManage/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.DeleteById",
		Path:    []string{"/v1/pluginsManage/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.DeleteByIds",
		Path:    []string{"/v1/pluginsManage/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.Update",
		Path:    []string{"/v1/pluginsManage/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.UpdateAll",
		Path:    []string{"/v1/pluginsManage/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.UpdateFields",
		Path:    []string{"/v1/pluginsManage/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.FindById",
		Path:    []string{"/v1/pluginsManage/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.Find",
		Path:    []string{"/v1/pluginsManage/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PluginsManageService.Lists",
		Path:    []string{"/v1/pluginsManage/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&PluginsManageService{h}, opts...))
}

type pluginsManageServiceHandler struct {
	PluginsManageServiceHandler
}

func (h *pluginsManageServiceHandler) Create(ctx context.Context, in *PluginsManage, out *Response) error {
	return h.PluginsManageServiceHandler.Create(ctx, in, out)
}

func (h *pluginsManageServiceHandler) Delete(ctx context.Context, in *PluginsManage, out *Response) error {
	return h.PluginsManageServiceHandler.Delete(ctx, in, out)
}

func (h *pluginsManageServiceHandler) DeleteById(ctx context.Context, in *PluginsManage, out *Response) error {
	return h.PluginsManageServiceHandler.DeleteById(ctx, in, out)
}

func (h *pluginsManageServiceHandler) DeleteByIds(ctx context.Context, in *PluginsManageBatchDeleteRequest, out *Response) error {
	return h.PluginsManageServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *pluginsManageServiceHandler) Update(ctx context.Context, in *PluginsManage, out *Response) error {
	return h.PluginsManageServiceHandler.Update(ctx, in, out)
}

func (h *pluginsManageServiceHandler) UpdateAll(ctx context.Context, in *PluginsManage, out *Response) error {
	return h.PluginsManageServiceHandler.UpdateAll(ctx, in, out)
}

func (h *pluginsManageServiceHandler) UpdateFields(ctx context.Context, in *PluginsManageUpdateFieldsRequest, out *Response) error {
	return h.PluginsManageServiceHandler.UpdateFields(ctx, in, out)
}

func (h *pluginsManageServiceHandler) FindById(ctx context.Context, in *PluginsManageFilter, out *PluginsManageResponse) error {
	return h.PluginsManageServiceHandler.FindById(ctx, in, out)
}

func (h *pluginsManageServiceHandler) Find(ctx context.Context, in *PluginsManageFilter, out *PluginsManageResponse) error {
	return h.PluginsManageServiceHandler.Find(ctx, in, out)
}

func (h *pluginsManageServiceHandler) Lists(ctx context.Context, in *PluginsManageListRequest, out *PluginsManageResponse) error {
	return h.PluginsManageServiceHandler.Lists(ctx, in, out)
}
