// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pm_thing_model_service.gen.proto

package protosService

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for PmThingModelService service

func NewPmThingModelServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "PmThingModelService.Create",
			Path:    []string{"/v1/pmThingModel/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.Delete",
			Path:    []string{"/v1/pmThingModel/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.DeleteById",
			Path:    []string{"/v1/pmThingModel/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.DeleteByIds",
			Path:    []string{"/v1/pmThingModel/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.Update",
			Path:    []string{"/v1/pmThingModel/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.UpdateAll",
			Path:    []string{"/v1/pmThingModel/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.UpdateFields",
			Path:    []string{"/v1/pmThingModel/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.FindById",
			Path:    []string{"/v1/pmThingModel/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.Find",
			Path:    []string{"/v1/pmThingModel/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "PmThingModelService.Lists",
			Path:    []string{"/v1/pmThingModel/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for PmThingModelService service

type PmThingModelService interface {
	//创建
	Create(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *PmThingModelBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *PmThingModelUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *PmThingModelFilter, opts ...client.CallOption) (*PmThingModelResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *PmThingModelFilter, opts ...client.CallOption) (*PmThingModelResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *PmThingModelListRequest, opts ...client.CallOption) (*PmThingModelResponse, error)
}

type pmThingModelService struct {
	c    client.Client
	name string
}

func NewPmThingModelService(name string, c client.Client) PmThingModelService {
	return &pmThingModelService{
		c:    c,
		name: name,
	}
}

func (c *pmThingModelService) Create(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) Delete(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) DeleteById(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) DeleteByIds(ctx context.Context, in *PmThingModelBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) Update(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) UpdateAll(ctx context.Context, in *PmThingModel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) UpdateFields(ctx context.Context, in *PmThingModelUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) FindById(ctx context.Context, in *PmThingModelFilter, opts ...client.CallOption) (*PmThingModelResponse, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.FindById", in)
	out := new(PmThingModelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) Find(ctx context.Context, in *PmThingModelFilter, opts ...client.CallOption) (*PmThingModelResponse, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.Find", in)
	out := new(PmThingModelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmThingModelService) Lists(ctx context.Context, in *PmThingModelListRequest, opts ...client.CallOption) (*PmThingModelResponse, error) {
	req := c.c.NewRequest(c.name, "PmThingModelService.Lists", in)
	out := new(PmThingModelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PmThingModelService service

type PmThingModelServiceHandler interface {
	//创建
	Create(context.Context, *PmThingModel, *Response) error
	//匹配多条件删除
	Delete(context.Context, *PmThingModel, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *PmThingModel, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *PmThingModelBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *PmThingModel, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *PmThingModel, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *PmThingModelUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *PmThingModelFilter, *PmThingModelResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *PmThingModelFilter, *PmThingModelResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *PmThingModelListRequest, *PmThingModelResponse) error
}

func RegisterPmThingModelServiceHandler(s server.Server, hdlr PmThingModelServiceHandler, opts ...server.HandlerOption) error {
	type pmThingModelService interface {
		Create(ctx context.Context, in *PmThingModel, out *Response) error
		Delete(ctx context.Context, in *PmThingModel, out *Response) error
		DeleteById(ctx context.Context, in *PmThingModel, out *Response) error
		DeleteByIds(ctx context.Context, in *PmThingModelBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *PmThingModel, out *Response) error
		UpdateAll(ctx context.Context, in *PmThingModel, out *Response) error
		UpdateFields(ctx context.Context, in *PmThingModelUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *PmThingModelFilter, out *PmThingModelResponse) error
		Find(ctx context.Context, in *PmThingModelFilter, out *PmThingModelResponse) error
		Lists(ctx context.Context, in *PmThingModelListRequest, out *PmThingModelResponse) error
	}
	type PmThingModelService struct {
		pmThingModelService
	}
	h := &pmThingModelServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.Create",
		Path:    []string{"/v1/pmThingModel/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.Delete",
		Path:    []string{"/v1/pmThingModel/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.DeleteById",
		Path:    []string{"/v1/pmThingModel/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.DeleteByIds",
		Path:    []string{"/v1/pmThingModel/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.Update",
		Path:    []string{"/v1/pmThingModel/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.UpdateAll",
		Path:    []string{"/v1/pmThingModel/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.UpdateFields",
		Path:    []string{"/v1/pmThingModel/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.FindById",
		Path:    []string{"/v1/pmThingModel/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.Find",
		Path:    []string{"/v1/pmThingModel/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "PmThingModelService.Lists",
		Path:    []string{"/v1/pmThingModel/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&PmThingModelService{h}, opts...))
}

type pmThingModelServiceHandler struct {
	PmThingModelServiceHandler
}

func (h *pmThingModelServiceHandler) Create(ctx context.Context, in *PmThingModel, out *Response) error {
	return h.PmThingModelServiceHandler.Create(ctx, in, out)
}

func (h *pmThingModelServiceHandler) Delete(ctx context.Context, in *PmThingModel, out *Response) error {
	return h.PmThingModelServiceHandler.Delete(ctx, in, out)
}

func (h *pmThingModelServiceHandler) DeleteById(ctx context.Context, in *PmThingModel, out *Response) error {
	return h.PmThingModelServiceHandler.DeleteById(ctx, in, out)
}

func (h *pmThingModelServiceHandler) DeleteByIds(ctx context.Context, in *PmThingModelBatchDeleteRequest, out *Response) error {
	return h.PmThingModelServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *pmThingModelServiceHandler) Update(ctx context.Context, in *PmThingModel, out *Response) error {
	return h.PmThingModelServiceHandler.Update(ctx, in, out)
}

func (h *pmThingModelServiceHandler) UpdateAll(ctx context.Context, in *PmThingModel, out *Response) error {
	return h.PmThingModelServiceHandler.UpdateAll(ctx, in, out)
}

func (h *pmThingModelServiceHandler) UpdateFields(ctx context.Context, in *PmThingModelUpdateFieldsRequest, out *Response) error {
	return h.PmThingModelServiceHandler.UpdateFields(ctx, in, out)
}

func (h *pmThingModelServiceHandler) FindById(ctx context.Context, in *PmThingModelFilter, out *PmThingModelResponse) error {
	return h.PmThingModelServiceHandler.FindById(ctx, in, out)
}

func (h *pmThingModelServiceHandler) Find(ctx context.Context, in *PmThingModelFilter, out *PmThingModelResponse) error {
	return h.PmThingModelServiceHandler.Find(ctx, in, out)
}

func (h *pmThingModelServiceHandler) Lists(ctx context.Context, in *PmThingModelListRequest, out *PmThingModelResponse) error {
	return h.PmThingModelServiceHandler.Lists(ctx, in, out)
}
