// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: sys_role_dept_service.gen.proto

package protosService

import (
	
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SysRoleDeptService service

func NewSysRoleDeptServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		{
			Name:    "SysRoleDeptService.Create",
			Path:    []string{"/v1/sysRoleDept/create"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.Delete",
			Path:    []string{"/v1/sysRoleDept/delete"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.DeleteById",
			Path:    []string{"/v1/sysRoleDept/deleteById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.DeleteByIds",
			Path:    []string{"/v1/sysRoleDept/DeleteByIds"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.Update",
			Path:    []string{"/v1/sysRoleDept/update"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.UpdateAll",
			Path:    []string{"/v1/sysRoleDept/updateAll"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.UpdateFields",
			Path:    []string{"/v1/sysRoleDept/updateFields"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.FindById",
			Path:    []string{"/v1/sysRoleDept/findById"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.Find",
			Path:    []string{"/v1/sysRoleDept/find"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
		{
			Name:    "SysRoleDeptService.Lists",
			Path:    []string{"/v1/sysRoleDept/lists"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for SysRoleDeptService service

type SysRoleDeptService interface {
	//创建
	Create(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error)
	//匹配多条件删除
	Delete(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error)
	//匹配主键删除,一般是Id
	DeleteById(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error)
	//匹配主键批量删除
	DeleteByIds(ctx context.Context, in *SysRoleDeptBatchDeleteRequest, opts ...client.CallOption) (*Response, error)
	//根据主键更新非空字段
	Update(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error)
	//根据主键更新所有字段
	UpdateAll(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error)
	//根据主键更新指定列
	UpdateFields(ctx context.Context, in *SysRoleDeptUpdateFieldsRequest, opts ...client.CallOption) (*Response, error)
	//根据主键查找,一般是Id,返回单条数据
	FindById(ctx context.Context, in *SysRoleDeptFilter, opts ...client.CallOption) (*SysRoleDeptResponse, error)
	//多条件查找，返回单条数据
	Find(ctx context.Context, in *SysRoleDeptFilter, opts ...client.CallOption) (*SysRoleDeptResponse, error)
	//查找，支持分页，可返回多条数据
	Lists(ctx context.Context, in *SysRoleDeptListRequest, opts ...client.CallOption) (*SysRoleDeptResponse, error)
}

type sysRoleDeptService struct {
	c    client.Client
	name string
}

func NewSysRoleDeptService(name string, c client.Client) SysRoleDeptService {
	return &sysRoleDeptService{
		c:    c,
		name: name,
	}
}

func (c *sysRoleDeptService) Create(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) Delete(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) DeleteById(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.DeleteById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) DeleteByIds(ctx context.Context, in *SysRoleDeptBatchDeleteRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.DeleteByIds", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) Update(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.Update", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) UpdateAll(ctx context.Context, in *SysRoleDept, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.UpdateAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) UpdateFields(ctx context.Context, in *SysRoleDeptUpdateFieldsRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.UpdateFields", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) FindById(ctx context.Context, in *SysRoleDeptFilter, opts ...client.CallOption) (*SysRoleDeptResponse, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.FindById", in)
	out := new(SysRoleDeptResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) Find(ctx context.Context, in *SysRoleDeptFilter, opts ...client.CallOption) (*SysRoleDeptResponse, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.Find", in)
	out := new(SysRoleDeptResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRoleDeptService) Lists(ctx context.Context, in *SysRoleDeptListRequest, opts ...client.CallOption) (*SysRoleDeptResponse, error) {
	req := c.c.NewRequest(c.name, "SysRoleDeptService.Lists", in)
	out := new(SysRoleDeptResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SysRoleDeptService service

type SysRoleDeptServiceHandler interface {
	//创建
	Create(context.Context, *SysRoleDept, *Response) error
	//匹配多条件删除
	Delete(context.Context, *SysRoleDept, *Response) error
	//匹配主键删除,一般是Id
	DeleteById(context.Context, *SysRoleDept, *Response) error
	//匹配主键批量删除
	DeleteByIds(context.Context, *SysRoleDeptBatchDeleteRequest, *Response) error
	//根据主键更新非空字段
	Update(context.Context, *SysRoleDept, *Response) error
	//根据主键更新所有字段
	UpdateAll(context.Context, *SysRoleDept, *Response) error
	//根据主键更新指定列
	UpdateFields(context.Context, *SysRoleDeptUpdateFieldsRequest, *Response) error
	//根据主键查找,一般是Id,返回单条数据
	FindById(context.Context, *SysRoleDeptFilter, *SysRoleDeptResponse) error
	//多条件查找，返回单条数据
	Find(context.Context, *SysRoleDeptFilter, *SysRoleDeptResponse) error
	//查找，支持分页，可返回多条数据
	Lists(context.Context, *SysRoleDeptListRequest, *SysRoleDeptResponse) error
}

func RegisterSysRoleDeptServiceHandler(s server.Server, hdlr SysRoleDeptServiceHandler, opts ...server.HandlerOption) error {
	type sysRoleDeptService interface {
		Create(ctx context.Context, in *SysRoleDept, out *Response) error
		Delete(ctx context.Context, in *SysRoleDept, out *Response) error
		DeleteById(ctx context.Context, in *SysRoleDept, out *Response) error
		DeleteByIds(ctx context.Context, in *SysRoleDeptBatchDeleteRequest, out *Response) error
		Update(ctx context.Context, in *SysRoleDept, out *Response) error
		UpdateAll(ctx context.Context, in *SysRoleDept, out *Response) error
		UpdateFields(ctx context.Context, in *SysRoleDeptUpdateFieldsRequest, out *Response) error
		FindById(ctx context.Context, in *SysRoleDeptFilter, out *SysRoleDeptResponse) error
		Find(ctx context.Context, in *SysRoleDeptFilter, out *SysRoleDeptResponse) error
		Lists(ctx context.Context, in *SysRoleDeptListRequest, out *SysRoleDeptResponse) error
	}
	type SysRoleDeptService struct {
		sysRoleDeptService
	}
	h := &sysRoleDeptServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.Create",
		Path:    []string{"/v1/sysRoleDept/create"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.Delete",
		Path:    []string{"/v1/sysRoleDept/delete"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.DeleteById",
		Path:    []string{"/v1/sysRoleDept/deleteById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.DeleteByIds",
		Path:    []string{"/v1/sysRoleDept/DeleteByIds"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.Update",
		Path:    []string{"/v1/sysRoleDept/update"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.UpdateAll",
		Path:    []string{"/v1/sysRoleDept/updateAll"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.UpdateFields",
		Path:    []string{"/v1/sysRoleDept/updateFields"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.FindById",
		Path:    []string{"/v1/sysRoleDept/findById"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.Find",
		Path:    []string{"/v1/sysRoleDept/find"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "SysRoleDeptService.Lists",
		Path:    []string{"/v1/sysRoleDept/lists"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&SysRoleDeptService{h}, opts...))
}

type sysRoleDeptServiceHandler struct {
	SysRoleDeptServiceHandler
}

func (h *sysRoleDeptServiceHandler) Create(ctx context.Context, in *SysRoleDept, out *Response) error {
	return h.SysRoleDeptServiceHandler.Create(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) Delete(ctx context.Context, in *SysRoleDept, out *Response) error {
	return h.SysRoleDeptServiceHandler.Delete(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) DeleteById(ctx context.Context, in *SysRoleDept, out *Response) error {
	return h.SysRoleDeptServiceHandler.DeleteById(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) DeleteByIds(ctx context.Context, in *SysRoleDeptBatchDeleteRequest, out *Response) error {
	return h.SysRoleDeptServiceHandler.DeleteByIds(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) Update(ctx context.Context, in *SysRoleDept, out *Response) error {
	return h.SysRoleDeptServiceHandler.Update(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) UpdateAll(ctx context.Context, in *SysRoleDept, out *Response) error {
	return h.SysRoleDeptServiceHandler.UpdateAll(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) UpdateFields(ctx context.Context, in *SysRoleDeptUpdateFieldsRequest, out *Response) error {
	return h.SysRoleDeptServiceHandler.UpdateFields(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) FindById(ctx context.Context, in *SysRoleDeptFilter, out *SysRoleDeptResponse) error {
	return h.SysRoleDeptServiceHandler.FindById(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) Find(ctx context.Context, in *SysRoleDeptFilter, out *SysRoleDeptResponse) error {
	return h.SysRoleDeptServiceHandler.Find(ctx, in, out)
}

func (h *sysRoleDeptServiceHandler) Lists(ctx context.Context, in *SysRoleDeptListRequest, out *SysRoleDeptResponse) error {
	return h.SysRoleDeptServiceHandler.Lists(ctx, in, out)
}
