// Code generated by protoc,2022-04-18 19:12:10. DO NOT EDIT.
// versions: v1.0.0
// 如果确实需要修改,请修改后改文件名,可以移除文件名中的.gen,以防下次生成覆盖

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: sys_user_online_model.gen.proto

package protosService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//来源于数据表
type SysUserOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"primary_key;AUTO_INCREMENT;default:;comment:;size:20;"
	Id int64 `protobuf:"varint,100,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"uuid" gorm:"default:用户标识;comment:用户标识;"
	Uuid string `protobuf:"bytes,101,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// @inject_tag: json:"token" gorm:"default:用户token;comment:用户token;size:255;"
	Token string `protobuf:"bytes,102,opt,name=token,proto3" json:"token,omitempty"`
	// @inject_tag: json:"createTime" gorm:"default:登录时间;comment:登录时间;"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @inject_tag: json:"userName" gorm:"default:用户名;comment:用户名;size:255;"
	UserName string `protobuf:"bytes,104,opt,name=userName,proto3" json:"userName,omitempty"`
	// @inject_tag: json:"ip" gorm:"default:登录ip;comment:登录ip;size:120;"
	Ip string `protobuf:"bytes,105,opt,name=ip,proto3" json:"ip,omitempty"`
	// @inject_tag: json:"explorer" gorm:"default:浏览器;comment:浏览器;size:30;"
	Explorer string `protobuf:"bytes,106,opt,name=explorer,proto3" json:"explorer,omitempty"`
	// @inject_tag: json:"os" gorm:"default:操作系统;comment:操作系统;size:30;"
	Os string `protobuf:"bytes,107,opt,name=os,proto3" json:"os,omitempty"`
}

func (x *SysUserOnline) Reset() {
	*x = SysUserOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnline) ProtoMessage() {}

func (x *SysUserOnline) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnline.ProtoReflect.Descriptor instead.
func (*SysUserOnline) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{0}
}

func (x *SysUserOnline) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysUserOnline) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SysUserOnline) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SysUserOnline) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SysUserOnline) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SysUserOnline) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SysUserOnline) GetExplorer() string {
	if x != nil {
		return x.Explorer
	}
	return ""
}

func (x *SysUserOnline) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type SysUserOnlineFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"primary_key;AUTO_INCREMENT;default:;comment:;size:20;"
	Id int64 `protobuf:"varint,100,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"uuid" gorm:"default:用户标识;comment:用户标识;"
	Uuid string `protobuf:"bytes,101,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// @inject_tag: json:"token" gorm:"default:用户token;comment:用户token;size:255;"
	Token string `protobuf:"bytes,102,opt,name=token,proto3" json:"token,omitempty"`
	// @inject_tag: json:"createTime" gorm:"default:登录时间;comment:登录时间;"
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// @inject_tag: json:"userName" gorm:"default:用户名;comment:用户名;size:255;"
	UserName string `protobuf:"bytes,104,opt,name=userName,proto3" json:"userName,omitempty"`
	// @inject_tag: json:"ip" gorm:"default:登录ip;comment:登录ip;size:120;"
	Ip string `protobuf:"bytes,105,opt,name=ip,proto3" json:"ip,omitempty"`
	// @inject_tag: json:"explorer" gorm:"default:浏览器;comment:浏览器;size:30;"
	Explorer string `protobuf:"bytes,106,opt,name=explorer,proto3" json:"explorer,omitempty"`
	// @inject_tag: json:"os" gorm:"default:操作系统;comment:操作系统;size:30;"
	Os string `protobuf:"bytes,107,opt,name=os,proto3" json:"os,omitempty"`
}

func (x *SysUserOnlineFilter) Reset() {
	*x = SysUserOnlineFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlineFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlineFilter) ProtoMessage() {}

func (x *SysUserOnlineFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlineFilter.ProtoReflect.Descriptor instead.
func (*SysUserOnlineFilter) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{1}
}

func (x *SysUserOnlineFilter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysUserOnlineFilter) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SysUserOnlineFilter) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SysUserOnlineFilter) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *SysUserOnlineFilter) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SysUserOnlineFilter) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SysUserOnlineFilter) GetExplorer() string {
	if x != nil {
		return x.Explorer
	}
	return ""
}

func (x *SysUserOnlineFilter) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type SysUserOnlineListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query     *SysUserOnline `protobuf:"bytes,101,opt,name=query,proto3" json:"query,omitempty"`
	Page      int64          `protobuf:"varint,102,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64          `protobuf:"varint,103,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderKey  string         `protobuf:"bytes,104,opt,name=orderKey,proto3" json:"orderKey,omitempty"`
	OrderDesc string         `protobuf:"bytes,105,opt,name=orderDesc,proto3" json:"orderDesc,omitempty"`
}

func (x *SysUserOnlineListRequest) Reset() {
	*x = SysUserOnlineListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlineListRequest) ProtoMessage() {}

func (x *SysUserOnlineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlineListRequest.ProtoReflect.Descriptor instead.
func (*SysUserOnlineListRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{2}
}

func (x *SysUserOnlineListRequest) GetQuery() *SysUserOnline {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SysUserOnlineListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SysUserOnlineListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SysUserOnlineListRequest) GetOrderKey() string {
	if x != nil {
		return x.OrderKey
	}
	return ""
}

func (x *SysUserOnlineListRequest) GetOrderDesc() string {
	if x != nil {
		return x.OrderDesc
	}
	return ""
}

type SysUserOnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32            `protobuf:"varint,101,opt,name=code,proto3" json:"code,omitempty"`
	Message string           `protobuf:"bytes,102,opt,name=message,proto3" json:"message,omitempty"`
	Total   int64            `protobuf:"varint,103,opt,name=total,proto3" json:"total,omitempty"`
	Data    []*SysUserOnline `protobuf:"bytes,104,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *SysUserOnlineResponse) Reset() {
	*x = SysUserOnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlineResponse) ProtoMessage() {}

func (x *SysUserOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlineResponse.ProtoReflect.Descriptor instead.
func (*SysUserOnlineResponse) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{3}
}

func (x *SysUserOnlineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SysUserOnlineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SysUserOnlineResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SysUserOnlineResponse) GetData() []*SysUserOnline {
	if x != nil {
		return x.Data
	}
	return nil
}

type SysUserOnlineUpdateFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []string       `protobuf:"bytes,101,rep,name=fields,proto3" json:"fields,omitempty"`
	Data   *SysUserOnline `protobuf:"bytes,102,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SysUserOnlineUpdateFieldsRequest) Reset() {
	*x = SysUserOnlineUpdateFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlineUpdateFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlineUpdateFieldsRequest) ProtoMessage() {}

func (x *SysUserOnlineUpdateFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlineUpdateFieldsRequest.ProtoReflect.Descriptor instead.
func (*SysUserOnlineUpdateFieldsRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{4}
}

func (x *SysUserOnlineUpdateFieldsRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *SysUserOnlineUpdateFieldsRequest) GetData() *SysUserOnline {
	if x != nil {
		return x.Data
	}
	return nil
}

// 表模型主键，只能是整数或字符串，若生成错误，请检查数据库表主键是否正确。支持组合主键
type SysUserOnlinePrimarykey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,100,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SysUserOnlinePrimarykey) Reset() {
	*x = SysUserOnlinePrimarykey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlinePrimarykey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlinePrimarykey) ProtoMessage() {}

func (x *SysUserOnlinePrimarykey) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlinePrimarykey.ProtoReflect.Descriptor instead.
func (*SysUserOnlinePrimarykey) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{5}
}

func (x *SysUserOnlinePrimarykey) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SysUserOnlineBatchDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []*SysUserOnlinePrimarykey `protobuf:"bytes,101,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *SysUserOnlineBatchDeleteRequest) Reset() {
	*x = SysUserOnlineBatchDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_user_online_model_gen_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysUserOnlineBatchDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysUserOnlineBatchDeleteRequest) ProtoMessage() {}

func (x *SysUserOnlineBatchDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sys_user_online_model_gen_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysUserOnlineBatchDeleteRequest.ProtoReflect.Descriptor instead.
func (*SysUserOnlineBatchDeleteRequest) Descriptor() ([]byte, []int) {
	return file_sys_user_online_model_gen_proto_rawDescGZIP(), []int{6}
}

func (x *SysUserOnlineBatchDeleteRequest) GetKeys() []*SysUserOnlinePrimarykey {
	if x != nil {
		return x.Keys
	}
	return nil
}

var File_sys_user_online_model_gen_proto protoreflect.FileDescriptor

var file_sys_user_online_model_gen_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x79, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x01, 0x0a, 0x0d,
	0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x65, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x66, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x69, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x18, 0x6a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x73, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x22, 0xe3, 0x01, 0x0a, 0x13,
	0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x65, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x66, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x67, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x69, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65,
	0x72, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x72, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x6b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f,
	0x73, 0x22, 0xb2, 0x01, 0x0a, 0x18, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x65, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x66, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x67, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x44, 0x65, 0x73, 0x63, 0x18, 0x69, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x44, 0x65, 0x73, 0x63, 0x22, 0x87, 0x01, 0x0a, 0x15, 0x53, 0x79, 0x73, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x65, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x66, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x67, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x68, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x79, 0x73,
	0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x66, 0x0a, 0x20, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x65,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x17, 0x53, 0x79, 0x73, 0x55,
	0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x1f, 0x53, 0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x65,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x79, 0x73, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x69, 0x6d,
	0x61, 0x72, 0x79, 0x6b, 0x65, 0x79, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_user_online_model_gen_proto_rawDescOnce sync.Once
	file_sys_user_online_model_gen_proto_rawDescData = file_sys_user_online_model_gen_proto_rawDesc
)

func file_sys_user_online_model_gen_proto_rawDescGZIP() []byte {
	file_sys_user_online_model_gen_proto_rawDescOnce.Do(func() {
		file_sys_user_online_model_gen_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_user_online_model_gen_proto_rawDescData)
	})
	return file_sys_user_online_model_gen_proto_rawDescData
}

var file_sys_user_online_model_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sys_user_online_model_gen_proto_goTypes = []interface{}{
	(*SysUserOnline)(nil),                    // 0: service.SysUserOnline
	(*SysUserOnlineFilter)(nil),              // 1: service.SysUserOnlineFilter
	(*SysUserOnlineListRequest)(nil),         // 2: service.SysUserOnlineListRequest
	(*SysUserOnlineResponse)(nil),            // 3: service.SysUserOnlineResponse
	(*SysUserOnlineUpdateFieldsRequest)(nil), // 4: service.SysUserOnlineUpdateFieldsRequest
	(*SysUserOnlinePrimarykey)(nil),          // 5: service.SysUserOnlinePrimarykey
	(*SysUserOnlineBatchDeleteRequest)(nil),  // 6: service.SysUserOnlineBatchDeleteRequest
	(*timestamppb.Timestamp)(nil),            // 7: google.protobuf.Timestamp
}
var file_sys_user_online_model_gen_proto_depIdxs = []int32{
	7, // 0: service.SysUserOnline.createTime:type_name -> google.protobuf.Timestamp
	7, // 1: service.SysUserOnlineFilter.createTime:type_name -> google.protobuf.Timestamp
	0, // 2: service.SysUserOnlineListRequest.query:type_name -> service.SysUserOnline
	0, // 3: service.SysUserOnlineResponse.data:type_name -> service.SysUserOnline
	0, // 4: service.SysUserOnlineUpdateFieldsRequest.data:type_name -> service.SysUserOnline
	5, // 5: service.SysUserOnlineBatchDeleteRequest.keys:type_name -> service.SysUserOnlinePrimarykey
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sys_user_online_model_gen_proto_init() }
func file_sys_user_online_model_gen_proto_init() {
	if File_sys_user_online_model_gen_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_user_online_model_gen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlineFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlineListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlineUpdateFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlinePrimarykey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_user_online_model_gen_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysUserOnlineBatchDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_user_online_model_gen_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_user_online_model_gen_proto_goTypes,
		DependencyIndexes: file_sys_user_online_model_gen_proto_depIdxs,
		MessageInfos:      file_sys_user_online_model_gen_proto_msgTypes,
	}.Build()
	File_sys_user_online_model_gen_proto = out.File
	file_sys_user_online_model_gen_proto_rawDesc = nil
	file_sys_user_online_model_gen_proto_goTypes = nil
	file_sys_user_online_model_gen_proto_depIdxs = nil
}
