package proto

import "errors"

type CommandStatus string

const (
	CommandStatusSuccess    CommandStatus = "SUCCESS"
	CommandStatusOFFLINE    CommandStatus = "OFFLINE"
	CommandStatusEXCEPTIONS CommandStatus = "EXCEPTIONS"
	CommandStatusError      CommandStatus = "ERROR"
)

type ErrorCode error

var (
	ErrorCodeAuthExpired     ErrorCode = errors.New("authExpired")
	ErrorCodeAuthFailure     ErrorCode = errors.New("authFailure")
	ErrorCodeDeviceOffline   ErrorCode = errors.New("deviceOffline")
	ErrorCodeTimeout         ErrorCode = errors.New("timeout")
	ErrorCodeDeviceTurnedOff ErrorCode = errors.New("deviceTurnedOff")
	ErrorCodeDeviceNotFound  ErrorCode = errors.New("deviceNotFound")
	ErrorCodeValueOutofRange ErrorCode = errors.New("valueOutOfRange")
	ErrorCodeNotSupported    ErrorCode = errors.New("notSupported")
	ErrorCodeProtocolError   ErrorCode = errors.New("protocolError")
	ErrorCodeUnknown         ErrorCode = errors.New("unknownError")
)

type DeviceError error

var (
	DeviceErrorAboveMaximumLightEffectsDuration DeviceError = errors.New("aboveMaximumLightEffectsDuration")
	DeviceErrorAboveMaximumTimerDuration        DeviceError = errors.New("aboveMaximumTimerDuration")
	DeviceErrorActionNotAvailable               DeviceError = errors.New("actionNotAvailable")
	DeviceErrorActionUnavailableWhileRunning    DeviceError = errors.New("actionUnavailableWhileRunning")
	DeviceErrorAlreadyArmed                     DeviceError = errors.New("alreadyArmed")
	DeviceErrorAlreadyAtMax                     DeviceError = errors.New("alreadyAtMax")
	DeviceErrorAlreadyAtMin                     DeviceError = errors.New("alreadyAtMin")
	DeviceErrorAlreadyClosed                    DeviceError = errors.New("alreadyClosed")
	DeviceErrorAlreadyDisarmed                  DeviceError = errors.New("alreadyDisarmed")
	DeviceErrorAlreadyDocked                    DeviceError = errors.New("alreadyDocked")
	DeviceErrorAlreadyInState                   DeviceError = errors.New("alreadyInState")
	DeviceErrorAlreadyLocked                    DeviceError = errors.New("alreadyLocked")
	DeviceErrorAlreadyOff                       DeviceError = errors.New("alreadyOff")
	DeviceErrorAlreadyOn                        DeviceError = errors.New("alreadyOn")
	DeviceErrorAlreadyOpen                      DeviceError = errors.New("alreadyOpen")
	DeviceErrorAlreadyPaused                    DeviceError = errors.New("alreadyPaused")
	DeviceErrorAlreadyStarted                   DeviceError = errors.New("alreadyStarted")
	DeviceErrorAlreadyStopped                   DeviceError = errors.New("alreadyStopped")
	DeviceErrorAlreadyUnlocked                  DeviceError = errors.New("alreadyUnlocked")
	DeviceErrorAmountAboveLimit                 DeviceError = errors.New("amountAboveLimit")
	DeviceErrorAppLaunchFailed                  DeviceError = errors.New("appLaunchFailed")
	DeviceErrorArmFailure                       DeviceError = errors.New("armFailure")
	DeviceErrorArmLevelNeeded                   DeviceError = errors.New("armLevelNeeded")
	DeviceErrorAuthFailure                      DeviceError = errors.New("authFailure")
	DeviceErrorBagFull                          DeviceError = errors.New("bagFull")
	DeviceErrorBelowMinimumLightEffectsDuration DeviceError = errors.New("belowMinimumLightEffectsDuration")
	DeviceErrorBelowMinimumTimerDuration        DeviceError = errors.New("belowMinimumTimerDuration")
	DeviceErrorBinFull                          DeviceError = errors.New("binFull")
	DeviceErrorCancelArmingRestricted           DeviceError = errors.New("cancelArmingRestricted")
	DeviceErrorCommandInsertFailed              DeviceError = errors.New("commandInsertFailed")
	DeviceErrorDegreesOutOfRange                DeviceError = errors.New("degreesOutOfRange")
	DeviceErrorDeviceDoorOpen                   DeviceError = errors.New("deviceDoorOpen")
	DeviceErrorDeviceHandleClosed               DeviceError = errors.New("deviceHandleClosed")
	DeviceErrorDeviceJammingDetected            DeviceError = errors.New("deviceJammingDetected")
	DeviceErrorDeviceLidOpen                    DeviceError = errors.New("deviceLidOpen")
	DeviceErrorDeviceNotDocked                  DeviceError = errors.New("deviceNotDocked")
	DeviceErrorDeviceNotFound                   DeviceError = errors.New("deviceNotFound")
	DeviceErrorDeviceNotReady                   DeviceError = errors.New("deviceNotReady")
	DeviceErrorDeviceStuck                      DeviceError = errors.New("deviceStuck")
	DeviceErrorDeviceTampered                   DeviceError = errors.New("deviceTampered")
	DeviceErrorDirectResponseOnlyUnreachable    DeviceError = errors.New("directResponseOnlyUnreachable")
	DeviceErrorDisarmFailure                    DeviceError = errors.New("disarmFailure")
	DeviceErrorDoorClosedTooLong                DeviceError = errors.New("doorClosedTooLong")
	DeviceErrorEmergencyHeatOn                  DeviceError = errors.New("emergencyHeatOn")
	DeviceErrorFloorUnreachable                 DeviceError = errors.New("floorUnreachable")
	DeviceErrorFunctionNotSupported             DeviceError = errors.New("functionNotSupported")
	DeviceErrorHardError                        DeviceError = errors.New("hardError")
	DeviceErrorInAutoMode                       DeviceError = errors.New("inAutoMode")
	DeviceErrorInAwayMode                       DeviceError = errors.New("inAwayMode")
	DeviceErrorInDryMode                        DeviceError = errors.New("inDryMode")
	DeviceErrorInEcoMode                        DeviceError = errors.New("inEcoMode")
	DeviceErrorInFanOnlyMode                    DeviceError = errors.New("inFanOnlyMode")
	DeviceErrorInHeatOrCool                     DeviceError = errors.New("inHeatOrCool")
	DeviceErrorInHumidifierMode                 DeviceError = errors.New("inHumidifierMode")
	DeviceErrorInOffMode                        DeviceError = errors.New("inOffMode")
	DeviceErrorInPurifierMode                   DeviceError = errors.New("inPurifierMode")
	DeviceErrorInSleepMode                      DeviceError = errors.New("inSleepMode")
	DeviceErrorLockFailure                      DeviceError = errors.New("lockFailure")
	DeviceErrorLockedToRange                    DeviceError = errors.New("lockedToRange")
	DeviceErrorLowBattery                       DeviceError = errors.New("lowBattery")
	DeviceErrorMaxSettingReached                DeviceError = errors.New("maxSettingReached")
	DeviceErrorMaxSpeedReached                  DeviceError = errors.New("maxSpeedReached")
	DeviceErrorMinSettingReached                DeviceError = errors.New("minSettingReached")
	DeviceErrorMinSpeedReached                  DeviceError = errors.New("minSpeedReached")
	DeviceErrorMissingSubscription              DeviceError = errors.New("missingSubscription")
	DeviceErrorNeedsAttachment                  DeviceError = errors.New("needsAttachment")
	DeviceErrorNeedsBin                         DeviceError = errors.New("needsBin")
	DeviceErrorNeedsPads                        DeviceError = errors.New("needsPads")
	DeviceErrorNeedsSoftwareUpdate              DeviceError = errors.New("needsSoftwareUpdate")
	DeviceErrorNeedsWater                       DeviceError = errors.New("needsWater")
	DeviceErrorNoAvailableApp                   DeviceError = errors.New("noAvailableApp")
	DeviceErrorNotSupported                     DeviceError = errors.New("notSupported")
	DeviceErrorObstructionDetected              DeviceError = errors.New("obstructionDetected")
	DeviceErrorOffline                          DeviceError = errors.New("offline")
	DeviceErrorOnRequiresMode                   DeviceError = errors.New("onRequiresMode")
	DeviceErrorPassphraseIncorrect              DeviceError = errors.New("passphraseIncorrect")
	DeviceErrorPinIncorrect                     DeviceError = errors.New("pinIncorrect")
	DeviceErrorRangeTooClose                    DeviceError = errors.New("rangeTooClose")
	DeviceErrorRelinkRequired                   DeviceError = errors.New("relinkRequired")
	DeviceErrorRoomsOnDifferentFloors           DeviceError = errors.New("roomsOnDifferentFloors")
	DeviceErrorSafetyShutOff                    DeviceError = errors.New("safetyShutOff")
	DeviceErrorSecurityRestriction              DeviceError = errors.New("securityRestriction")
	DeviceErrorSoftwareUpdateNotAvailable       DeviceError = errors.New("softwareUpdateNotAvailable")
	DeviceErrorStartRequiresTime                DeviceError = errors.New("startRequiresTime")
	DeviceErrorStillWarmingUp                   DeviceError = errors.New("stillWarmingUp")
	DeviceErrorTankEmpty                        DeviceError = errors.New("tankEmpty")
	DeviceErrorTargetAlreadyReached             DeviceError = errors.New("targetAlreadyReached")
	DeviceErrorTimerValueOutOfRange             DeviceError = errors.New("timerValueOutOfRange")
	DeviceErrorTransientError                   DeviceError = errors.New("transientError")
	DeviceErrorTurnedOff                        DeviceError = errors.New("turnedOff")
	DeviceErrorUnableToLocateDevice             DeviceError = errors.New("unableToLocateDevice")
	DeviceErrorUnknownFoodPreset                DeviceError = errors.New("unknownFoodPreset")
	DeviceErrorUnlockFailure                    DeviceError = errors.New("unlockFailure")
	DeviceErrorValueOutOfRange                  DeviceError = errors.New("valueOutOfRange")
)

var (
	ErrSyncFailed        = errors.New("sync failed")
	ErrReportStateFailed = errors.New("report state failed")
)
