// Code generated by sgen.exe,2022-10-24 09:40:33. DO NOT EDIT.
// versions: v1.0.0
//  API结构体封装，请自行根据需要删减字段修改

package entitys

import (
	proto "cloud_platform/iot_proto/protos/protosService"
)

// 增、删、改及查询返回
type OemAppTemplateDeveloperEntitys struct {
	Id            int64  `json:"id,string,omitempty"`
	AppTemplateId int64  `json:"appTemplateId,string,omitempty"`
	DeveloperId   int64  `json:"developerId,string,omitempty"`
	TenantId      string `json:"tenantId,omitempty"`
}

// 新增参数非空检查
func (s *OemAppTemplateDeveloperEntitys) AddCheck() error {
	return nil
}

// 修改参数非空检查
func (s *OemAppTemplateDeveloperEntitys) UpdateCheck() error {
	return nil
}

// 查询参数必填检查
func (*OemAppTemplateDeveloperQuery) QueryCheck() error {
	return nil
}

// 查询条件
type OemAppTemplateDeveloperQuery struct {
	Page      uint64                         `json:"page,omitempty"`
	Limit     uint64                         `json:"limit,omitempty"`
	Sort      string                         `json:"sort,omitempty"`
	SortField string                         `json:"sortField,omitempty"`
	SearchKey string                         `json:"searchKey,omitempty"`
	Query     *OemAppTemplateDeveloperFilter `json:"query,omitempty"`
}

// OemAppTemplateDeveloperFilter，查询条件，字段请根据需要自行增减
type OemAppTemplateDeveloperFilter struct {
	Id            int64  `json:"id,string,omitempty"`
	AppTemplateId int64  `json:"appTemplateId,string,omitempty"`
	DeveloperId   int64  `json:"developerId,string,omitempty"`
	TenantId      string `json:"tenantId,omitempty"`
}

// 实体转pb对象
func OemAppTemplateDeveloper_e2pb(src *OemAppTemplateDeveloperEntitys) *proto.OemAppTemplateDeveloper {
	if src == nil {
		return nil
	}
	pbObj := proto.OemAppTemplateDeveloper{
		Id:            src.Id,
		AppTemplateId: src.AppTemplateId,
		DeveloperId:   src.DeveloperId,
		TenantId:      src.TenantId,
	}
	return &pbObj
}

// pb对象转实体
func OemAppTemplateDeveloper_pb2e(src *proto.OemAppTemplateDeveloper) *OemAppTemplateDeveloperEntitys {
	if src == nil {
		return nil
	}
	entitysObj := OemAppTemplateDeveloperEntitys{
		Id:            src.Id,
		AppTemplateId: src.AppTemplateId,
		DeveloperId:   src.DeveloperId,
		TenantId:      src.TenantId,
	}
	return &entitysObj
}
