// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTDemoGenTree = "t_demo_gen_tree"

// TDemoGenTree mapped from table <t_demo_gen_tree>
type TDemoGenTree struct {
	Id          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentId    int32          `gorm:"column:parent_id;not null;default:0" json:"parentId"`        // 父级ID
	DemoName    string         `gorm:"column:demo_name;not null;default:''" json:"demoName"`       // 姓名
	DemoAge     int32          `gorm:"column:demo_age;not null;default:0" json:"demoAge"`          // 年龄
	Classes     string         `gorm:"column:classes;not null;default:''" json:"classes"`          // 班级
	DemoBorn    time.Time      `gorm:"column:demo_born" json:"demoBorn"`                           // 出生年月
	TDemoGender int32          `gorm:"column:t_demo_gender;not null;default:0" json:"tDemoGender"` // 性别
	CreatedAt   time.Time      `gorm:"column:created_at" json:"createdAt"`                         // 创建日期
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updatedAt"`                         // 修改日期
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                         // 删除日期
	CreatedBy   int64          `gorm:"column:created_by;not null;default:0" json:"createdBy"`      // 创建人
	UpdatedBy   int64          `gorm:"column:updated_by;not null;default:0" json:"updatedBy"`      // 修改人
	DemoStatus  int32          `gorm:"column:demo_status;not null;default:0" json:"demoStatus"`    // 状态
	DemoCate    string         `gorm:"column:demo_cate;not null;default:''" json:"demoCate"`       // 分类
}

// TableName TDemoGenTree's table name
func (*TDemoGenTree) TableName() string {
	return TableNameTDemoGenTree
}
